from typing import Protocol


class DataProvider(Protocol):
    """Interface for dashboard data access. All methods return JSON-serializable dicts."""

    def overview(self, filters: dict) -> dict: ...
    def tokens(self, filters: dict) -> dict: ...
    def tools(self, filters: dict) -> dict: ...
    def concurrency(self, filters: dict) -> dict: ...
    def summarization(self, filters: dict) -> dict: ...
    def sessions(self, filters: dict) -> dict: ...
    def session_detail(self, session_id: str) -> dict: ...
    def session_replay(self, session_id: str, jsonl_dir: str) -> dict: ...
    def compare(self, filters_a: dict, filters_b: dict) -> dict: ...
    def activity_heatmap(self, filters: dict) -> dict: ...
    def latency(self, filters: dict) -> dict: ...
    def errors(self, filters: dict) -> dict: ...
