#!/usr/bin/env python3
"""
MCP Router - Passthrough router with response summarization.

Routes MCP requests to registered target servers, returns responses
with {summary, full} envelope where summary is Haiku-generated.

Usage:
    from mcp_router import MCPRouter, RouterResponse

    router = MCPRouter()
    router.register_server("serena", ["python", "-m", "serena"], {"tool_prefix": "serena"})
    response = router.route("serena", "find_symbol", {"name": "MyClass"})
    print(response.summary)  # Haiku-generated summary
    print(response.full)     # Full response (access only if needed)
"""

import hashlib
import json
import os
import subprocess
import sys
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timezone
import socket
from threading import Lock, Thread
from pathlib import Path
from typing import Any, Callable, Optional

try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    anthropic = None  # type: ignore
    ANTHROPIC_AVAILABLE = False

try:
    import openai
    OPENAI_AVAILABLE = True
except ImportError:
    openai = None  # type: ignore
    OPENAI_AVAILABLE = False

# Import v2 telemetry schema functions
from telemetry_schema_v2 import (
    TelemetryV2,
    load_telemetry_v2,
    save_telemetry_v2,
    ensure_day,
    update_timing_stats,
)


@dataclass
class RouterResponse:
    """Response envelope with summary and full response.

    The summary is generated by Haiku and should be sufficient for most cases.
    Access .full only when you need the complete response data.
    """
    summary: str
    full: Any
    correlation_id: str = ""

    def __repr__(self):
        return (
            f"RouterResponse(\n"
            f"  summary={self.summary!r},\n"
            f"  full=<available - access only if needed>,\n"
            f"  correlation_id={self.correlation_id!r}\n"
            f")"
        )

    def __str__(self):
        return (
            f"Summary: {self.summary}\n"
            f"[Full response available via .full - access only if needed]"
        )


@dataclass
class ServerConfig:
    """Configuration for a registered MCP server."""
    name: str
    command: list[str]
    args: dict = field(default_factory=dict)
    tool_prefix: str = ""
    registered_at: str = ""

    def __post_init__(self):
        if not self.registered_at:
            self.registered_at = datetime.now(timezone.utc).isoformat()


@dataclass
class TelemetryEvent:
    """Single telemetry event."""
    timestamp: str
    tool: str
    backend: str
    duration_ms: int
    status: str  # "success" | "error"
    tokens_est: int = 0
    subagent_type: str = ""
    error_msg: str = ""


class TelemetryCollector:
    """Real-time telemetry collection for MCP router using v2 schema.

    Tracks all tool calls, durations, token estimates, and errors.
    Writes to telemetry.json on every event for real-time dashboard updates.
    Uses the unified v2 telemetry schema.
    """

    # Token estimates by tool type (conservative estimates)
    TOKEN_ESTIMATES = {
        "read_file": 2000,
        "find_symbol": 1500,
        "search_for_pattern": 1500,
        "get_symbols_overview": 1000,
        "list_dir": 500,
        "find_file": 500,
        "replace_content": 800,
        "replace_symbol_body": 1000,
        "insert_after_symbol": 800,
        "insert_before_symbol": 800,
        "execute_shell_command": 1000,
    }

    # Subagent token estimates (much larger)
    SUBAGENT_TOKEN_ESTIMATES = {
        "Explore": 25000,
        "Plan": 30000,
        "Implement": 100000,
        "general-purpose": 50000,
        "Bash": 10000,
        "feature-dev:code-explorer": 40000,
        "feature-dev:code-reviewer": 30000,
        "feature-dev:code-architect": 50000,
    }

    def __init__(
        self,
        telemetry_file: Optional[Path] = None,
        max_events: int = 500
    ):
        """Initialize telemetry collector.

        Args:
            telemetry_file: Path to write telemetry JSON
            max_events: Maximum events to keep (rolling window)
        """
        self._telemetry_file = telemetry_file or Path.home() / ".claude/plugins/agent-swarm/.state/telemetry.json"
        self._max_events = max_events
        self._lock = Lock()
        self._pending_requests: dict[str, tuple[str, str, dict, float]] = {}
        self._session_id = datetime.now(timezone.utc).isoformat()
        self._events: list[dict] = []  # Session events (rolling window)
        self._data: TelemetryV2 = load_telemetry_v2(self._telemetry_file)

    def _save(self) -> None:
        """Save telemetry to file using v2 schema."""
        save_telemetry_v2(self._data, self._telemetry_file)

    def _estimate_tokens(self, tool: str, subagent_type: str = "") -> int:
        """Estimate tokens for a tool call."""
        if subagent_type:
            return self.SUBAGENT_TOKEN_ESTIMATES.get(subagent_type, 50000)
        base_tool = tool.split("__")[-1] if "__" in tool else tool
        return self.TOKEN_ESTIMATES.get(base_tool, 500)

    def _get_today_key(self) -> str:
        """Get today's date key in YYYY-MM-DD format."""
        return datetime.now(timezone.utc).strftime("%Y-%m-%d")

    def track_request(self, destination: str, tool_name: str, args: dict) -> str:
        """Called when a request is made. Returns correlation_id."""
        import time
        correlation_id = f"req-{int(time.time() * 1000)}-{hash((destination, tool_name)) & 0xFFFF:04x}"

        with self._lock:
            self._pending_requests[correlation_id] = (
                tool_name, destination, args, time.time()
            )
        return correlation_id

    def track_response(
        self,
        correlation_id: str,
        error: bool = False,
        error_msg: str = "",
        full_size: int = 0,
        summary_size: int = 0
    ) -> None:
        """Called when a response is received.

        Args:
            correlation_id: Request correlation ID
            error: Whether the request errored
            error_msg: Error message if any
            full_size: Size of full response in chars (for efficiency tracking)
            summary_size: Size of summary in chars (for efficiency tracking)
        """
        import time

        with self._lock:
            if correlation_id not in self._pending_requests:
                return

            tool_name, backend, args, start_time = self._pending_requests.pop(correlation_id)
            duration_ms = int((time.time() - start_time) * 1000)

            # Check for subagent
            subagent_type = args.get("subagent_type", "") if tool_name == "Task" else ""
            tokens_est = self._estimate_tokens(tool_name, subagent_type)

            # Create event for session tracking
            event = {
                "ts": datetime.now(timezone.utc).isoformat(),
                "tool": tool_name,
                "backend": backend,
                "duration_ms": duration_ms,
                "status": "error" if error else "success",
                "tokens_est": tokens_est,
                "subagent_type": subagent_type,
                "error_msg": error_msg[:200] if error_msg else "",
                "full_size": full_size,
                "summary_size": summary_size
            }

            # Add to session events (rolling window)
            self._events.append(event)
            if len(self._events) > self._max_events:
                self._events = self._events[-self._max_events:]

            # Update v2 telemetry
            self._update_v2_telemetry(event, error, full_size, summary_size, duration_ms)

            # Save immediately for real-time updates
            self._save()

    def _update_v2_telemetry(
        self,
        event: dict,
        error: bool,
        full_size: int,
        summary_size: int,
        duration_ms: int
    ) -> None:
        """Update v2 telemetry structure."""
        day_key = self._get_today_key()
        day_data = ensure_day(self._data, day_key)

        # Update call counts
        calls = day_data.setdefault("calls", {"total": 0, "by_tool": {}, "by_backend": {}})
        calls["total"] = calls.get("total", 0) + 1

        tool = event["tool"]
        calls.setdefault("by_tool", {})[tool] = calls.get("by_tool", {}).get(tool, 0) + 1

        backend = event["backend"]
        calls.setdefault("by_backend", {})[backend] = calls.get("by_backend", {}).get(backend, 0) + 1

        # Update timing stats
        timing = day_data.setdefault("timing", {"avg_response_ms": 0.0, "p95_response_ms": 0.0, "by_backend": {}})
        update_timing_stats(timing, backend, duration_ms)

        # Update summarization stats if applicable
        if full_size > 0 and summary_size > 0:
            summ = day_data.setdefault("summarization", {
                "offered": 0, "accepted": 0, "rejected": 0,
                "acceptance_rate": 0.0, "tokens_saved_est": 0
            })
            summ["offered"] = summ.get("offered", 0) + 1
            summ["accepted"] = summ.get("accepted", 0) + 1  # Router always accepts
            chars_saved = full_size - summary_size
            tokens_saved = chars_saved // 4  # ~4 chars per token
            summ["tokens_saved_est"] = summ.get("tokens_saved_est", 0) + tokens_saved
            total = summ.get("offered", 1)
            summ["acceptance_rate"] = summ.get("accepted", 0) / total if total > 0 else 0.0

        # Track session
        sessions = day_data.setdefault("sessions", [])
        if self._session_id not in sessions:
            sessions.append(self._session_id)

    def get_summary(self) -> dict:
        """Get current telemetry summary."""
        with self._lock:
            day_key = self._get_today_key()
            day_data = self._data.get("days", {}).get(day_key, {})

            calls = day_data.get("calls", {})
            timing = day_data.get("timing", {})
            summ = day_data.get("summarization", {})

            # Compute efficiency metrics from summarization data
            tokens_saved = summ.get("tokens_saved_est", 0)
            offered = summ.get("offered", 0)

            return {
                "session_id": self._session_id,
                "event_count": len(self._events),
                "today": day_key,
                "aggregates": {
                    "by_tool": calls.get("by_tool", {}),
                    "by_backend": calls.get("by_backend", {}),
                    "totals": {"calls": calls.get("total", 0)},
                    "timing": timing,
                    "efficiency": {
                        "calls_summarized": offered,
                        "tokens_saved_est": tokens_saved,
                    }
                },
                "recent_events": self._events[-10:]  # Last 10
            }




class MCPRouter:
    """Thread-safe MCP request router with backpressure handling.

    Routes requests to registered target servers, summarizes responses,
    and returns {summary, full} envelope.

    Connections are spawned on first use and kept alive for reuse.
    Per-backend locks ensure safe concurrent access.

    Summarizer options:
        - "openai": Use OpenAI API (requires OPENAI_API_KEY)
        - "anthropic": Use Anthropic API (requires ANTHROPIC_API_KEY)
        - "none": Use fallback heuristics only

    Hook points:
        on_request: Called before forwarding (destination, tool, args)
        on_response: Called after response packaged (RouterResponse)
    """

    # Default models for each provider
    DEFAULT_MODELS = {
        "openai": "gpt-4o-mini",
        "anthropic": "claude-3-5-haiku-20241022",
    }

    def __init__(
        self,
        max_queue_size: int = 1000,
        summarizer: str = "auto",
        summarizer_model: Optional[str] = None,
        enable_telemetry: bool = True,
    ):
        """Initialize router with request queue and lock.

        Args:
            max_queue_size: Maximum pending requests before blocking.
            summarizer: Provider for summarization ("auto", "openai", "anthropic", "none").
                        "auto" tries openai first, then anthropic, then falls back.
            summarizer_model: Model to use (defaults based on provider).
            enable_telemetry: Enable real-time telemetry collection.
        """
        self._queue: deque = deque(maxlen=max_queue_size)
        self._lock = Lock()
        self._servers: dict[str, ServerConfig] = {}
        self._connections: dict[str, subprocess.Popen] = {}  # Live backend processes
        self._backend_locks: dict[str, Lock] = {}  # Per-backend locks

        # Initialize summarizer (decide provider once at startup)
        self._llm_call: Callable[[str], str] = self._init_summarizer(summarizer, summarizer_model)

        # Hook points for extensibility (logging, telemetry, testing)
        self.on_request: list[Callable[[str, str, dict], None]] = []
        self.on_response: list[Callable[[RouterResponse], None]] = []

        # Telemetry collector for real-time metrics
        self.telemetry: Optional[TelemetryCollector] = TelemetryCollector() if enable_telemetry else None

        # Socket listener for external clients (hooks, CLIs)
        self._socket_server: Optional[socket.socket] = None
        self._socket_thread: Optional[Thread] = None
        self._socket_port: int = 0
        self._socket_running: bool = False
        self._port_file = Path(__file__).parent.parent / ".state" / "router.port"

    def _init_summarizer(
        self,
        provider: str,
        model: Optional[str]
    ) -> Callable[[str], str]:
        """Initialize summarizer and return the LLM call function.

        Decides provider at startup, returns a simple prompt->response function.
        """
        # Auto-detect: try openai, then anthropic
        if provider == "auto":
            if OPENAI_AVAILABLE and os.environ.get("OPENAI_API_KEY"):
                provider = "openai"
            elif ANTHROPIC_AVAILABLE and os.environ.get("ANTHROPIC_API_KEY"):
                provider = "anthropic"
            else:
                provider = "none"

        if provider == "openai":
            return self._init_openai(model or self.DEFAULT_MODELS["openai"])
        elif provider == "anthropic":
            return self._init_anthropic(model or self.DEFAULT_MODELS["anthropic"])
        else:
            return lambda prompt: ""  # Empty = use fallback

    def _init_openai(self, model: str) -> Callable[[str], str]:
        """Initialize OpenAI client and return call function."""
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key or not OPENAI_AVAILABLE:
            return lambda prompt: ""

        client = openai.OpenAI(api_key=api_key)

        def call(prompt: str) -> str:
            try:
                response = client.chat.completions.create(
                    model=model,
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=500,
                    temperature=0,
                )
                return response.choices[0].message.content.strip()
            except Exception:
                return ""

        return call

    def _init_anthropic(self, model: str) -> Callable[[str], str]:
        """Initialize Anthropic client and return call function."""
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key or not ANTHROPIC_AVAILABLE:
            return lambda prompt: ""

        client = anthropic.Anthropic(api_key=api_key)

        def call(prompt: str) -> str:
            try:
                response = client.messages.create(
                    model=model,
                    max_tokens=500,
                    temperature=0,
                    messages=[{"role": "user", "content": prompt}],
                )
                return response.content[0].text.strip()
            except Exception:
                return ""

        return call

    # === Registration API ===

    def register_server(
        self,
        name: str,
        command: list[str],
        args: Optional[dict] = None,
        tool_prefix: str = ""
    ) -> dict:
        """Register an MCP server for routing.

        Args:
            name: Unique server identifier
            command: Subprocess command to spawn server
            args: Optional initialization arguments
            tool_prefix: Prefix for tool names from this server

        Returns:
            Registration confirmation dict
        """
        with self._lock:
            config = ServerConfig(
                name=name,
                command=command,
                args=args or {},
                tool_prefix=tool_prefix
            )
            self._servers[name] = config

            return {
                "status": "registered",
                "name": name,
                "tool_prefix": tool_prefix,
                "registered_at": config.registered_at
            }

    def unregister_server(self, name: str) -> dict:
        """Remove a registered server.

        Args:
            name: Server identifier to remove

        Returns:
            Confirmation dict
        """
        with self._lock:
            existed = self._servers.pop(name, None) is not None
            # Kill connection if exists
            proc = self._connections.pop(name, None)
            if proc:
                proc.terminate()
            return {
                "status": "unregistered" if existed else "not_found",
                "name": name
            }

    def shutdown(self) -> None:
        """Shutdown all backend connections and socket listener."""
        # Stop socket listener first
        self.stop_socket_listener()

        with self._lock:
            for _, proc in list(self._connections.items()):
                try:
                    proc.terminate()
                    proc.wait(timeout=5)
                except Exception:
                    proc.kill()
            self._connections.clear()

    # ─────────────────────────────────────────────────────────────
    # Socket Listener for External Clients
    # ─────────────────────────────────────────────────────────────

    def start_socket_listener(self, port: int = 0) -> int:
        """Start socket listener for external clients (hooks, CLIs).

        Args:
            port: Port to listen on (0 for auto-assign).

        Returns:
            The actual port being used.
        """
        self._socket_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._socket_server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self._socket_server.bind(("127.0.0.1", port))
        self._socket_server.listen(5)
        self._socket_port = self._socket_server.getsockname()[1]
        self._socket_running = True

        # Write port to file for client discovery
        self._port_file.parent.mkdir(parents=True, exist_ok=True)
        self._port_file.write_text(str(self._socket_port))

        # Start accept loop in background thread
        self._socket_thread = Thread(target=self._socket_accept_loop, daemon=True)
        self._socket_thread.start()

        return self._socket_port

    def stop_socket_listener(self) -> None:
        """Stop socket listener and clean up port file."""
        self._socket_running = False
        if self._socket_server:
            try:
                self._socket_server.close()
            except Exception:
                pass
        if self._port_file.exists():
            try:
                self._port_file.unlink()
            except Exception:
                pass

    def _socket_accept_loop(self) -> None:
        """Accept connections and spawn handler threads."""
        while self._socket_running:
            try:
                self._socket_server.settimeout(1.0)  # Check running flag periodically
                try:
                    client, _ = self._socket_server.accept()
                    Thread(target=self._handle_socket_client, args=(client,), daemon=True).start()
                except socket.timeout:
                    continue
            except Exception:
                if self._socket_running:
                    continue
                break

    def _handle_socket_client(self, client: socket.socket) -> None:
        """Handle a single client connection.

        Reads JSON-RPC request, routes it, sends response.
        Connection is closed after one request-response cycle.
        """
        try:
            # Read request (newline-delimited JSON)
            data = b""
            while b"\n" not in data:
                chunk = client.recv(4096)
                if not chunk:
                    return
                data += chunk

            request = json.loads(data.decode().strip())
            request_id = request.get("id")
            method = request.get("method", "")
            params = request.get("params", {})

            # Route the request (same logic as stdio)
            if method == "tools/call":
                tool_name = params.get("name", "")
                args = params.get("arguments", {})

                if "__" in tool_name:
                    prefix, actual_tool = tool_name.split("__", 1)
                    # Find backend by prefix
                    destination = None
                    for server in self.list_servers():
                        if server.get("tool_prefix") == prefix or server["name"] == prefix:
                            destination = server["name"]
                            break

                    if not destination:
                        result = {"content": [{"type": "text", "text": f"Error: Unknown backend prefix: {prefix}"}], "isError": True}
                    else:
                        response = self.route(destination, actual_tool, args)
                        backend_result = response.full
                        if isinstance(backend_result, dict) and "error" in backend_result:
                            result = {"content": [{"type": "text", "text": f"Error: {backend_result['error']}"}], "isError": True}
                        else:
                            if isinstance(backend_result, dict) and "result" in backend_result:
                                full_content = backend_result["result"]
                            else:
                                full_content = backend_result
                            result = full_content
                else:
                    result = {"content": [{"type": "text", "text": "Tool name must be prefixed: prefix__tool"}], "isError": True}
            else:
                result = {"error": f"Unsupported method: {method}"}

            # Send response
            response = {
                "jsonrpc": "2.0",
                "id": request_id,
                "result": result
            }
            client.sendall(json.dumps(response).encode() + b"\n")

        except Exception as e:
            try:
                error_response = {
                    "jsonrpc": "2.0",
                    "id": None,
                    "error": {"code": -32603, "message": str(e)}
                }
                client.sendall(json.dumps(error_response).encode() + b"\n")
            except Exception:
                pass
        finally:
            try:
                client.close()
            except Exception:
                pass

    def list_servers(self) -> list[dict]:
        """List all registered servers.

        Returns:
            List of server info dicts
        """
        with self._lock:
            return [
                {
                    "name": s.name,
                    "command": s.command,
                    "tool_prefix": s.tool_prefix,
                    "registered_at": s.registered_at
                }
                for s in self._servers.values()
            ]

    # === Routing ===

    def route(
        self,
        destination: str,
        tool_name: str,
        args: dict
    ) -> RouterResponse:
        """Route a tool request to target server.

        Args:
            destination: Target server name
            tool_name: Tool to invoke
            args: Tool arguments

        Returns:
            RouterResponse with structured summary and full response
        """
        correlation_id = self._generate_correlation_id(destination, tool_name, args)

        # Start telemetry tracking
        telemetry_id = None
        if self.telemetry:
            telemetry_id = self.telemetry.track_request(destination, tool_name, args)

        # Fire request hooks
        for hook in self.on_request:
            try:
                hook(destination, tool_name, args)
            except Exception:
                pass  # Don't let hooks break routing

        # Get target server
        with self._lock:
            server = self._servers.get(destination)

        error = False
        error_msg = ""

        if not server:
            error = True
            error_msg = f"Server '{destination}' not registered"
            response = RouterResponse(
                summary=f"Error: {error_msg}",
                full={"error": error_msg},
                correlation_id=correlation_id
            )
        else:
            # Forward request
            full_response = self._forward_to_server(server, tool_name, args)

            # Check for error in response
            if isinstance(full_response, dict) and "error" in full_response:
                error = True
                error_msg = str(full_response.get("error", "Unknown error"))[:200]

            # Generate structured summary using schema extraction
            summary = self._extract_summary(tool_name, full_response)

            response = RouterResponse(
                summary=summary,
                full=full_response,
                correlation_id=correlation_id
            )

        # Calculate sizes for efficiency tracking
        full_size = len(json.dumps(response.full)) if response.full else 0
        summary_size = len(response.summary) if response.summary else 0

        # Fire response hooks
        for hook in self.on_response:
            try:
                hook(response)
            except Exception:
                pass  # Don't let hooks break response

        # Complete telemetry tracking
        if self.telemetry and telemetry_id:
            self.telemetry.track_response(
                telemetry_id,
                error=error,
                error_msg=error_msg,
                full_size=full_size,
                summary_size=summary_size
            )

        return response

    def _generate_correlation_id(
        self,
        destination: str,
        tool_name: str,
        args: dict
    ) -> str:
        """Generate correlation ID from request parameters.

        Uses hash of args for deterministic IDs (same request = same ID).
        """
        content = json.dumps({
            "destination": destination,
            "tool": tool_name,
            "args": args
        }, sort_keys=True)
        hash_digest = hashlib.sha256(content.encode()).hexdigest()[:12]
        return f"req-{hash_digest}"

    def _get_backend_lock(self, server_name: str) -> Lock:
        """Get or create lock for a backend server."""
        with self._lock:
            if server_name not in self._backend_locks:
                self._backend_locks[server_name] = Lock()
            return self._backend_locks[server_name]

    def _get_connection(self, server: ServerConfig) -> subprocess.Popen:
        """Get existing connection or spawn new one with handshake.

        Args:
            server: Target server config

        Returns:
            Live subprocess connection

        Raises:
            RuntimeError: If connection cannot be established
        """
        # Return existing connection if we have one
        if server.name in self._connections:
            return self._connections[server.name]

        # Spawn new process
        proc = subprocess.Popen(
            server.command,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1  # Line buffered
        )

        def send(msg: dict) -> None:
            """Send JSON-RPC message to server."""
            line = json.dumps(msg) + "\n"
            proc.stdin.write(line)  # type: ignore[union-attr]
            proc.stdin.flush()  # type: ignore[union-attr]

        def receive() -> dict:
            """Receive JSON-RPC response from server."""
            line = proc.stdout.readline()  # type: ignore[union-attr]
            if not line:
                raise RuntimeError("Server closed connection")
            return json.loads(line.strip())

        # MCP handshake
        try:
            send({
                "jsonrpc": "2.0",
                "id": 1,
                "method": "initialize",
                "params": {
                    "protocolVersion": "2024-11-05",
                    "capabilities": {},
                    "clientInfo": {
                        "name": "mcp-router",
                        "version": "1.0.0"
                    }
                }
            })

            init_response = receive()
            if "error" in init_response:
                proc.kill()
                raise RuntimeError(f"Initialize failed: {init_response['error']}")

            send({
                "jsonrpc": "2.0",
                "method": "notifications/initialized"
            })
        except Exception as e:
            proc.kill()
            raise RuntimeError(f"Handshake failed: {e}")

        # Store connection
        self._connections[server.name] = proc
        return proc

    def _forward_to_server(
        self,
        server: ServerConfig,
        tool_name: str,
        args: dict
    ) -> dict:
        """Forward request to target MCP server.

        Uses persistent connection (spawns on first use, reuses thereafter).
        Per-backend lock ensures safe concurrent access.

        Args:
            server: Target server config
            tool_name: Tool to invoke
            args: Tool arguments

        Returns:
            Response dict from target server
        """
        backend_lock = self._get_backend_lock(server.name)

        with backend_lock:
            try:
                proc = self._get_connection(server)

                # Build request
                request_id = hash((tool_name, json.dumps(args, sort_keys=True))) & 0xFFFFFFFF

                if tool_name == "__list__":
                    # Special: get tool list
                    request = {
                        "jsonrpc": "2.0",
                        "id": request_id,
                        "method": "tools/list",
                        "params": {}
                    }
                else:
                    # Normal tool call
                    request = {
                        "jsonrpc": "2.0",
                        "id": request_id,
                        "method": "tools/call",
                        "params": {
                            "name": tool_name,
                            "arguments": args
                        }
                    }

                line = json.dumps(request) + "\n"
                proc.stdin.write(line)  # type: ignore[union-attr]
                proc.stdin.flush()  # type: ignore[union-attr]

                # Receive response
                response_line = proc.stdout.readline()  # type: ignore[union-attr]
                if not response_line:
                    # Connection died, remove and retry once
                    self._connections.pop(server.name, None)
                    return self._forward_to_server(server, tool_name, args)

                return json.loads(response_line.strip())

            except json.JSONDecodeError as e:
                self._connections.pop(server.name, None)
                return {"error": f"Invalid JSON response: {e}"}
            except Exception as e:
                self._connections.pop(server.name, None)
                return {"error": str(e)}

    # === Summarization ===

    def _summarize(self, response: dict) -> str:
        """Generate summary of response using configured LLM.

        Args:
            response: Response dict to summarize

        Returns:
            Summary string (or fallback on error)
        """
        content = json.dumps(response, indent=2)[:2000]

        prompt = f"""Summarize this MCP tool response in 1-2 concise sentences.
Focus on what was accomplished or returned.

Response:
{content}

Summary:"""

        result = self._llm_call(prompt)
        return result if result else self._fallback_summary(response)

    def _fallback_summary(self, response: dict) -> str:
        """Generate fallback summary when Haiku unavailable.

        Args:
            response: Response dict

        Returns:
            Basic summary string
        """
        if "error" in response:
            return f"Error: {response['error'][:100]}"

        # Try to extract meaningful info
        if "result" in response:
            result = response["result"]
            if isinstance(result, list):
                return f"Returned {len(result)} items"
            elif isinstance(result, dict):
                keys = list(result.keys())[:3]
                return f"Returned object with keys: {', '.join(keys)}"
            elif isinstance(result, str):
                return f"Returned string ({len(result)} chars)"

        return f"Response received ({len(json.dumps(response))} chars)"

    # Output schemas for structured extraction
    TOOL_SCHEMAS: dict[str, dict] = {
        "grep": {
            "description": "Search results grouped by file with line numbers",
            "schema": {
                "files": "list of matching file paths",
                "by_file": "dict mapping filepath to list of line numbers where matches occur",
                "match_count": "total number of matches"
            }
        },
        "glob": {
            "description": "File listing grouped by directory",
            "schema": {
                "by_directory": "dict mapping directory path to list of filenames in that directory",
                "total": "total number of files found"
            }
        },
        "bash": {
            "description": "Command execution result. If output contains [stderr] marker, that indicates error output.",
            "schema": {
                "exit_code": "0 for success, non-zero if [stderr] present or command failed",
                "line_count": "number of output lines",
                "preview": "first 5 lines of output (list of strings)",
                "error": "content after [stderr] marker if present, null otherwise"
            }
        },
        "read_file": {
            "description": "File contents",
            "schema": {
                "line_count": "number of lines in file",
                "char_count": "number of characters",
                "preview": "first 10 lines of content"
            }
        },
        "write_file": {
            "description": "File write result",
            "schema": {
                "success": "true if file was written successfully",
                "error": "error message if failed, null otherwise"
            }
        },
        "edit_file": {
            "description": "File edit result",
            "schema": {
                "success": "true if edit was applied successfully",
                "error": "error message if failed, null otherwise"
            }
        }
    }

    GENERIC_SCHEMA = {
        "description": "Generic tool output",
        "schema": {
            "char_count": "total characters in output",
            "preview": "first 500 characters of output",
            "truncated": "true if output was truncated"
        }
    }

    def _extract_summary(self, tool_name: str, response: dict) -> str:
        """Generate structured summary using LLM to extract into schema.

        Args:
            tool_name: Name of the tool that produced the response
            response: Response dict from backend

        Returns:
            JSON string with structured summary
        """
        if "error" in response:
            return json.dumps({"error": str(response["error"])[:200]})

        # Get raw content from MCP response
        content = self._extract_content(response)

        # For bash with stderr, use fallback directly (LLM struggles with [stderr] marker)
        if tool_name == "bash" and "[stderr]" in content:
            return self._fallback_extract(tool_name, content)

        # Get schema for this tool (or generic)
        tool_schema = self.TOOL_SCHEMAS.get(tool_name, self.GENERIC_SCHEMA)

        # Use LLM to extract into schema
        prompt = f"""Transform this tool output into the following JSON schema.
Return ONLY valid JSON, no explanation.
Limit any lists to first 10 items max.

Schema: {json.dumps(tool_schema["schema"])}
Tool output (truncated to 2000 chars):
{content[:2000]}

JSON:"""

        result = self._llm_call(prompt)

        # Validate it's JSON, fallback if not
        if result:
            try:
                json.loads(result)
                return result
            except json.JSONDecodeError:
                pass

        # Fallback: basic extraction without LLM
        return self._fallback_extract(tool_name, content)

    def _extract_content(self, response: dict) -> str:
        """Extract raw text content from MCP response."""
        if "result" in response:
            result = response["result"]
            if isinstance(result, dict):
                content_list = result.get("content", [])
                if content_list and isinstance(content_list[0], dict):
                    return content_list[0].get("text", "")
            elif isinstance(result, str):
                return result
        return json.dumps(response)

    def _fallback_extract(self, tool_name: str, content: str) -> str:
        """Fallback extraction when LLM unavailable."""
        lines = content.split("\n")

        if tool_name in ("write_file", "edit_file"):
            return json.dumps({"success": "error" not in content.lower()})

        if tool_name == "bash":
            # [stderr] marker indicates error output was present
            has_stderr = "[stderr]" in content
            stderr_content = None
            if has_stderr:
                parts = content.split("[stderr]")
                stderr_content = parts[1].strip() if len(parts) > 1 else "stderr present"
            return json.dumps({
                "exit_code": 1 if has_stderr else 0,
                "line_count": len(lines),
                "preview": lines[:5],
                "error": stderr_content
            })

        # Generic fallback
        return json.dumps({
            "char_count": len(content),
            "preview": content[:500],
            "truncated": len(content) > 500
        })


def analyze_telemetry_trends(telemetry: TelemetryCollector) -> dict:
    """Analyze telemetry data for trends and effectiveness.

    Returns analysis of token usage patterns and optimization effectiveness.
    Works with v2 telemetry schema.
    """
    summary = telemetry.get_summary()
    events = summary.get("recent_events", [])
    agg = summary.get("aggregates", {})

    analysis = {
        "session_id": summary.get("session_id", ""),
        "total_events": summary.get("event_count", 0),
        "today": summary.get("today", ""),
        "totals": agg.get("totals", {}),
        "trends": {},
        "recommendations": []
    }

    if len(events) >= 10:
        # Compare first half vs second half of events
        mid = len(events) // 2
        first_half = events[:mid]
        second_half = events[mid:]

        first_tokens = sum(e.get("tokens_est", 0) for e in first_half)
        second_tokens = sum(e.get("tokens_est", 0) for e in second_half)

        if first_tokens > 0:
            change_pct = ((second_tokens - first_tokens) / first_tokens) * 100
            analysis["trends"]["token_change_pct"] = round(change_pct, 1)
            analysis["trends"]["first_half_tokens"] = first_tokens
            analysis["trends"]["second_half_tokens"] = second_tokens

            if change_pct < -10:
                analysis["trends"]["verdict"] = "IMPROVING"
                analysis["recommendations"].append(
                    "Token usage is decreasing - optimization measures appear effective"
                )
            elif change_pct > 10:
                analysis["trends"]["verdict"] = "INCREASING"
                analysis["recommendations"].append(
                    "Token usage is increasing - consider reviewing recent tool usage patterns"
                )
            else:
                analysis["trends"]["verdict"] = "STABLE"

    # Check for high-call tools (v2 schema has counts, not token totals per tool)
    by_tool = agg.get("by_tool", {})
    high_call_tools = [
        (tool, count)
        for tool, count in by_tool.items()
        if isinstance(count, int) and count > 50
    ]
    if high_call_tools:
        sorted_tools = sorted(high_call_tools, key=lambda x: x[1], reverse=True)[:3]
        analysis["top_tool_callers"] = [
            {"tool": t, "calls": v} for t, v in sorted_tools
        ]
        analysis["recommendations"].append(
            f"High call count in: {', '.join(t for t, _ in sorted_tools)}"
        )

    # Timing analysis
    timing = agg.get("timing", {})
    by_backend = timing.get("by_backend", {})
    slow_backends = [
        (backend, stats.get("avg_ms", 0))
        for backend, stats in by_backend.items()
        if isinstance(stats, dict) and stats.get("avg_ms", 0) > 1000
    ]
    if slow_backends:
        analysis["slow_backends"] = [
            {"backend": b, "avg_ms": round(ms, 1)} for b, ms in slow_backends
        ]
        analysis["recommendations"].append(
            f"Slow response times from: {', '.join(b for b, _ in slow_backends)}"
        )

    # Summarization efficiency
    efficiency = agg.get("efficiency", {})
    tokens_saved = efficiency.get("tokens_saved_est", 0)
    if tokens_saved > 0:
        analysis["tokens_saved_est"] = tokens_saved
        analysis["recommendations"].append(
            f"Summarization saved approximately {tokens_saved} tokens"
        )

    return analysis


# === stdio Server ===

def start_stdio_server(router: MCPRouter):
    """Run stdio-based MCP server loop.

    Reads JSON-RPC requests from stdin, routes through router,
    writes responses to stdout.

    Implements MCP protocol:
    - initialize/initialized handshake
    - tools/list (aggregates from all backends, prefixes tool names)
    - tools/call (routes based on prefix)
    """
    def send(msg: dict) -> None:
        print(json.dumps(msg), flush=True)

    def list_all_tools() -> list[dict]:
        """Get tools from all backends, prefix names with backend."""
        # Router's own tools
        all_tools = [
            {
                "name": "router__ping",
                "description": "Test tool that returns a simple message",
                "inputSchema": {"type": "object", "properties": {}},
            },
            {
                "name": "router__telemetry",
                "description": "Get real-time telemetry data (tool usage, tokens, errors, timing)",
                "inputSchema": {"type": "object", "properties": {}},
            },
            {
                "name": "router__telemetry_analysis",
                "description": "Get analysis of token usage trends and optimization effectiveness",
                "inputSchema": {"type": "object", "properties": {}},
            },
        ]
        for server in router.list_servers():
            name = server["name"]
            prefix = server.get("tool_prefix") or name

            # Get tools from this backend
            try:
                response = router._forward_to_server(
                    router._servers[name],
                    "__list__",  # Special: triggers tools/list
                    {}
                )
                if "result" in response and "tools" in response["result"]:
                    for tool in response["result"]["tools"]:
                        # Prefix tool name
                        tool["name"] = f"{prefix}__{tool['name']}"
                        all_tools.append(tool)
            except Exception:
                pass  # Skip failed backends
        return all_tools

    for line in sys.stdin:
        request_id = None
        try:
            request = json.loads(line.strip())
            method = request.get("method", "")
            params = request.get("params", {})
            request_id = request.get("id")

            # MCP handshake
            if method == "initialize":
                result = {
                    "protocolVersion": "2024-11-05",
                    "capabilities": {"tools": {}},
                    "serverInfo": {
                        "name": "mcp-router",
                        "version": "1.0.0"
                    }
                }
            elif method == "notifications/initialized":
                continue  # Notification, no response

            # Tool discovery
            elif method == "tools/list":
                result = {"tools": list_all_tools()}

            # Tool execution - parse prefix to route
            elif method == "tools/call":
                tool_name = params.get("name", "")
                args = params.get("arguments", {})

                # Handle router's own tools first
                if tool_name == "router__ping":
                    result = {"content": [{"type": "text", "text": "pong! Router is working."}]}

                elif tool_name == "router__telemetry":
                    if router.telemetry:
                        summary = router.telemetry.get_summary()
                        result = {"content": [{"type": "text", "text": json.dumps(summary, indent=2)}]}
                    else:
                        result = {"content": [{"type": "text", "text": "Telemetry not enabled"}]}

                elif tool_name == "router__telemetry_analysis":
                    if router.telemetry:
                        analysis = analyze_telemetry_trends(router.telemetry)
                        result = {"content": [{"type": "text", "text": json.dumps(analysis, indent=2)}]}
                    else:
                        result = {"content": [{"type": "text", "text": "Telemetry not enabled"}]}

                # Parse prefix__toolname for backend routing
                elif "__" in tool_name:
                    prefix, actual_tool = tool_name.split("__", 1)
                    # Find backend by prefix
                    destination = None
                    for server in router.list_servers():
                        if server.get("tool_prefix") == prefix or server["name"] == prefix:
                            destination = server["name"]
                            break
                    if not destination:
                        result = {"content": [{"type": "text", "text": f"Error: Unknown backend prefix: {prefix}"}], "isError": True}
                    else:
                        response = router.route(destination, actual_tool, args)
                        # Return {summary, full} envelope so Claude can read summary first
                        backend_result = response.full
                        if isinstance(backend_result, dict) and "error" in backend_result:
                            result = {"content": [{"type": "text", "text": f"Error: {backend_result['error']}"}], "isError": True}
                        else:
                            # Extract actual content from backend response
                            if isinstance(backend_result, dict) and "result" in backend_result:
                                full_content = backend_result["result"]
                            else:
                                full_content = backend_result

                            # Return structured envelope with summary and full
                            envelope = {
                                "summary": response.summary,
                                "full": full_content
                            }
                            result = {"content": [{"type": "text", "text": json.dumps(envelope)}]}
                else:
                    result = {"content": [{"type": "text", "text": "Tool name must be prefixed: prefix__tool"}], "isError": True}

            # Router management API
            elif method == "router_register":
                result = router.register_server(**params)
            elif method == "router_list":
                result = router.list_servers()
            elif method == "router_unregister":
                result = router.unregister_server(**params)

            else:
                result = {"error": f"Unknown method: {method}"}

            # Write response (skip for notifications)
            if request_id is not None:
                send({
                    "jsonrpc": "2.0",
                    "id": request_id,
                    "result": result
                })

        except json.JSONDecodeError as e:
            send({
                "jsonrpc": "2.0",
                "id": request_id,
                "error": {"code": -32700, "message": f"Parse error: {e}"}
            })
        except Exception as e:
            send({
                "jsonrpc": "2.0",
                "id": request_id,
                "error": {"code": -32603, "message": str(e)}
            })


if __name__ == "__main__":
    router = MCPRouter()

    # Auto-register default server from env if specified
    default_server = os.environ.get("MCP_ROUTER_DEFAULT_SERVER")
    if default_server:
        router.register_server("default", default_server.split(), {})

    # Start socket listener for external clients (hooks, CLIs)
    port = router.start_socket_listener()
    sys.stderr.write(f"Router socket listener started on port {port}\n")

    try:
        start_stdio_server(router)
    finally:
        router.shutdown()
