#!/usr/bin/env python3
"""
MCP Router - Passthrough router with response summarization.

Routes MCP requests to registered target servers, returns responses
with {summary, full} envelope where summary is Haiku-generated.

Usage:
    from mcp_router import MCPRouter, RouterResponse

    router = MCPRouter()
    router.register_server("serena", ["python", "-m", "serena"], {"tool_prefix": "serena"})
    response = router.route("serena", "find_symbol", {"name": "MyClass"})
    print(response.summary)  # Haiku-generated summary
    print(response.full)     # Full response (access only if needed)
"""

import hashlib
import json
import os
import subprocess
import sys
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timezone
from threading import Lock
from typing import Any, Callable, Optional

try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    anthropic = None  # type: ignore
    ANTHROPIC_AVAILABLE = False

try:
    import openai
    OPENAI_AVAILABLE = True
except ImportError:
    openai = None  # type: ignore
    OPENAI_AVAILABLE = False


@dataclass
class RouterResponse:
    """Response envelope with summary and full response.

    The summary is generated by Haiku and should be sufficient for most cases.
    Access .full only when you need the complete response data.
    """
    summary: str
    full: Any
    correlation_id: str = ""

    def __repr__(self):
        return (
            f"RouterResponse(\n"
            f"  summary={self.summary!r},\n"
            f"  full=<available - access only if needed>,\n"
            f"  correlation_id={self.correlation_id!r}\n"
            f")"
        )

    def __str__(self):
        return (
            f"Summary: {self.summary}\n"
            f"[Full response available via .full - access only if needed]"
        )


@dataclass
class ServerConfig:
    """Configuration for a registered MCP server."""
    name: str
    command: list[str]
    args: dict = field(default_factory=dict)
    tool_prefix: str = ""
    registered_at: str = ""

    def __post_init__(self):
        if not self.registered_at:
            self.registered_at = datetime.now(timezone.utc).isoformat()


class MCPRouter:
    """Thread-safe MCP request router with backpressure handling.

    Routes requests to registered target servers, summarizes responses,
    and returns {summary, full} envelope.

    Connections are spawned on first use and kept alive for reuse.
    Per-backend locks ensure safe concurrent access.

    Summarizer options:
        - "openai": Use OpenAI API (requires OPENAI_API_KEY)
        - "anthropic": Use Anthropic API (requires ANTHROPIC_API_KEY)
        - "none": Use fallback heuristics only

    Hook points:
        on_request: Called before forwarding (destination, tool, args)
        on_response: Called after response packaged (RouterResponse)
    """

    # Default models for each provider
    DEFAULT_MODELS = {
        "openai": "gpt-4o-mini",
        "anthropic": "claude-3-5-haiku-20241022",
    }

    def __init__(
        self,
        max_queue_size: int = 1000,
        summarizer: str = "auto",
        summarizer_model: Optional[str] = None,
    ):
        """Initialize router with request queue and lock.

        Args:
            max_queue_size: Maximum pending requests before blocking.
            summarizer: Provider for summarization ("auto", "openai", "anthropic", "none").
                        "auto" tries openai first, then anthropic, then falls back.
            summarizer_model: Model to use (defaults based on provider).
        """
        self._queue: deque = deque(maxlen=max_queue_size)
        self._lock = Lock()
        self._servers: dict[str, ServerConfig] = {}
        self._connections: dict[str, subprocess.Popen] = {}  # Live backend processes
        self._backend_locks: dict[str, Lock] = {}  # Per-backend locks

        # Initialize summarizer (decide provider once at startup)
        self._llm_call: Callable[[str], str] = self._init_summarizer(summarizer, summarizer_model)

        # Hook points for extensibility (logging, telemetry, testing)
        self.on_request: list[Callable[[str, str, dict], None]] = []
        self.on_response: list[Callable[[RouterResponse], None]] = []

    def _init_summarizer(
        self,
        provider: str,
        model: Optional[str]
    ) -> Callable[[str], str]:
        """Initialize summarizer and return the LLM call function.

        Decides provider at startup, returns a simple prompt->response function.
        """
        # Auto-detect: try openai, then anthropic
        if provider == "auto":
            if OPENAI_AVAILABLE and os.environ.get("OPENAI_API_KEY"):
                provider = "openai"
            elif ANTHROPIC_AVAILABLE and os.environ.get("ANTHROPIC_API_KEY"):
                provider = "anthropic"
            else:
                provider = "none"

        if provider == "openai":
            return self._init_openai(model or self.DEFAULT_MODELS["openai"])
        elif provider == "anthropic":
            return self._init_anthropic(model or self.DEFAULT_MODELS["anthropic"])
        else:
            return lambda prompt: ""  # Empty = use fallback

    def _init_openai(self, model: str) -> Callable[[str], str]:
        """Initialize OpenAI client and return call function."""
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key or not OPENAI_AVAILABLE:
            return lambda prompt: ""

        client = openai.OpenAI(api_key=api_key)

        def call(prompt: str) -> str:
            try:
                response = client.chat.completions.create(
                    model=model,
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=100,
                    temperature=0,
                )
                return response.choices[0].message.content.strip()
            except Exception:
                return ""

        return call

    def _init_anthropic(self, model: str) -> Callable[[str], str]:
        """Initialize Anthropic client and return call function."""
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key or not ANTHROPIC_AVAILABLE:
            return lambda prompt: ""

        client = anthropic.Anthropic(api_key=api_key)

        def call(prompt: str) -> str:
            try:
                response = client.messages.create(
                    model=model,
                    max_tokens=100,
                    temperature=0,
                    messages=[{"role": "user", "content": prompt}],
                )
                return response.content[0].text.strip()
            except Exception:
                return ""

        return call

    # === Registration API ===

    def register_server(
        self,
        name: str,
        command: list[str],
        args: Optional[dict] = None,
        tool_prefix: str = ""
    ) -> dict:
        """Register an MCP server for routing.

        Args:
            name: Unique server identifier
            command: Subprocess command to spawn server
            args: Optional initialization arguments
            tool_prefix: Prefix for tool names from this server

        Returns:
            Registration confirmation dict
        """
        with self._lock:
            config = ServerConfig(
                name=name,
                command=command,
                args=args or {},
                tool_prefix=tool_prefix
            )
            self._servers[name] = config

            return {
                "status": "registered",
                "name": name,
                "tool_prefix": tool_prefix,
                "registered_at": config.registered_at
            }

    def unregister_server(self, name: str) -> dict:
        """Remove a registered server.

        Args:
            name: Server identifier to remove

        Returns:
            Confirmation dict
        """
        with self._lock:
            existed = self._servers.pop(name, None) is not None
            # Kill connection if exists
            proc = self._connections.pop(name, None)
            if proc:
                proc.terminate()
            return {
                "status": "unregistered" if existed else "not_found",
                "name": name
            }

    def shutdown(self) -> None:
        """Shutdown all backend connections."""
        with self._lock:
            for _, proc in list(self._connections.items()):
                try:
                    proc.terminate()
                    proc.wait(timeout=5)
                except Exception:
                    proc.kill()
            self._connections.clear()

    def list_servers(self) -> list[dict]:
        """List all registered servers.

        Returns:
            List of server info dicts
        """
        with self._lock:
            return [
                {
                    "name": s.name,
                    "command": s.command,
                    "tool_prefix": s.tool_prefix,
                    "registered_at": s.registered_at
                }
                for s in self._servers.values()
            ]

    # === Routing ===

    def route(
        self,
        destination: str,
        tool_name: str,
        args: dict
    ) -> RouterResponse:
        """Route a tool request to target server.

        Args:
            destination: Target server name
            tool_name: Tool to invoke
            args: Tool arguments

        Returns:
            RouterResponse with summary and full response
        """
        correlation_id = self._generate_correlation_id(destination, tool_name, args)

        # Fire request hooks
        for hook in self.on_request:
            try:
                hook(destination, tool_name, args)
            except Exception:
                pass  # Don't let hooks break routing

        # Get target server
        with self._lock:
            server = self._servers.get(destination)

        if not server:
            response = RouterResponse(
                summary=f"Error: Server '{destination}' not registered",
                full={"error": f"Server '{destination}' not registered"},
                correlation_id=correlation_id
            )
        else:
            # Forward request
            full_response = self._forward_to_server(server, tool_name, args)

            # Generate summary
            summary = self._summarize(full_response)

            response = RouterResponse(
                summary=summary,
                full=full_response,
                correlation_id=correlation_id
            )

        # Fire response hooks
        for hook in self.on_response:
            try:
                hook(response)
            except Exception:
                pass  # Don't let hooks break response

        return response

    def _generate_correlation_id(
        self,
        destination: str,
        tool_name: str,
        args: dict
    ) -> str:
        """Generate correlation ID from request parameters.

        Uses hash of args for deterministic IDs (same request = same ID).
        """
        content = json.dumps({
            "destination": destination,
            "tool": tool_name,
            "args": args
        }, sort_keys=True)
        hash_digest = hashlib.sha256(content.encode()).hexdigest()[:12]
        return f"req-{hash_digest}"

    def _get_backend_lock(self, server_name: str) -> Lock:
        """Get or create lock for a backend server."""
        with self._lock:
            if server_name not in self._backend_locks:
                self._backend_locks[server_name] = Lock()
            return self._backend_locks[server_name]

    def _get_connection(self, server: ServerConfig) -> subprocess.Popen:
        """Get existing connection or spawn new one with handshake.

        Args:
            server: Target server config

        Returns:
            Live subprocess connection

        Raises:
            RuntimeError: If connection cannot be established
        """
        # Return existing connection if we have one
        if server.name in self._connections:
            return self._connections[server.name]

        # Spawn new process
        proc = subprocess.Popen(
            server.command,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1  # Line buffered
        )

        def send(msg: dict) -> None:
            """Send JSON-RPC message to server."""
            line = json.dumps(msg) + "\n"
            proc.stdin.write(line)  # type: ignore[union-attr]
            proc.stdin.flush()  # type: ignore[union-attr]

        def receive() -> dict:
            """Receive JSON-RPC response from server."""
            line = proc.stdout.readline()  # type: ignore[union-attr]
            if not line:
                raise RuntimeError("Server closed connection")
            return json.loads(line.strip())

        # MCP handshake
        try:
            send({
                "jsonrpc": "2.0",
                "id": 1,
                "method": "initialize",
                "params": {
                    "protocolVersion": "2024-11-05",
                    "capabilities": {},
                    "clientInfo": {
                        "name": "mcp-router",
                        "version": "1.0.0"
                    }
                }
            })

            init_response = receive()
            if "error" in init_response:
                proc.kill()
                raise RuntimeError(f"Initialize failed: {init_response['error']}")

            send({
                "jsonrpc": "2.0",
                "method": "notifications/initialized"
            })
        except Exception as e:
            proc.kill()
            raise RuntimeError(f"Handshake failed: {e}")

        # Store connection
        self._connections[server.name] = proc
        return proc

    def _forward_to_server(
        self,
        server: ServerConfig,
        tool_name: str,
        args: dict
    ) -> dict:
        """Forward request to target MCP server.

        Uses persistent connection (spawns on first use, reuses thereafter).
        Per-backend lock ensures safe concurrent access.

        Args:
            server: Target server config
            tool_name: Tool to invoke
            args: Tool arguments

        Returns:
            Response dict from target server
        """
        backend_lock = self._get_backend_lock(server.name)

        with backend_lock:
            try:
                proc = self._get_connection(server)

                # Send tool call
                request_id = hash((tool_name, json.dumps(args, sort_keys=True))) & 0xFFFFFFFF
                line = json.dumps({
                    "jsonrpc": "2.0",
                    "id": request_id,
                    "method": "tools/call",
                    "params": {
                        "name": tool_name,
                        "arguments": args
                    }
                }) + "\n"
                proc.stdin.write(line)  # type: ignore[union-attr]
                proc.stdin.flush()  # type: ignore[union-attr]

                # Receive response
                response_line = proc.stdout.readline()  # type: ignore[union-attr]
                if not response_line:
                    # Connection died, remove and retry once
                    self._connections.pop(server.name, None)
                    return self._forward_to_server(server, tool_name, args)

                return json.loads(response_line.strip())

            except json.JSONDecodeError as e:
                self._connections.pop(server.name, None)
                return {"error": f"Invalid JSON response: {e}"}
            except Exception as e:
                self._connections.pop(server.name, None)
                return {"error": str(e)}

    # === Summarization ===

    def _summarize(self, response: dict) -> str:
        """Generate summary of response using configured LLM.

        Args:
            response: Response dict to summarize

        Returns:
            Summary string (or fallback on error)
        """
        content = json.dumps(response, indent=2)[:2000]

        prompt = f"""Summarize this MCP tool response in 1-2 concise sentences.
Focus on what was accomplished or returned.

Response:
{content}

Summary:"""

        result = self._llm_call(prompt)
        return result if result else self._fallback_summary(response)

    def _fallback_summary(self, response: dict) -> str:
        """Generate fallback summary when Haiku unavailable.

        Args:
            response: Response dict

        Returns:
            Basic summary string
        """
        if "error" in response:
            return f"Error: {response['error'][:100]}"

        # Try to extract meaningful info
        if "result" in response:
            result = response["result"]
            if isinstance(result, list):
                return f"Returned {len(result)} items"
            elif isinstance(result, dict):
                keys = list(result.keys())[:3]
                return f"Returned object with keys: {', '.join(keys)}"
            elif isinstance(result, str):
                return f"Returned string ({len(result)} chars)"

        return f"Response received ({len(json.dumps(response))} chars)"


# === stdio Server ===

def start_stdio_server(router: MCPRouter):
    """Run stdio-based MCP server loop.

    Reads JSON-RPC requests from stdin, routes through router,
    writes responses to stdout.
    """
    for line in sys.stdin:
        request_id = None
        try:
            request = json.loads(line.strip())
            method = request.get("method", "")
            params = request.get("params", {})
            request_id = request.get("id")

            # Handle router API
            if method == "router_register":
                result = router.register_server(**params)
            elif method == "router_list":
                result = router.list_servers()
            elif method == "router_unregister":
                result = router.unregister_server(**params)
            elif method == "tools/call":
                # Route to target server
                destination = params.get("destination", "default")
                tool_name = params.get("name", "")
                args = params.get("arguments", {})
                response = router.route(destination, tool_name, args)
                result = {
                    "summary": response.summary,
                    "full": response.full,
                    "correlation_id": response.correlation_id
                }
            else:
                result = {"error": f"Unknown method: {method}"}

            # Write response
            response_obj = {
                "jsonrpc": "2.0",
                "id": request_id,
                "result": result
            }
            print(json.dumps(response_obj), flush=True)

        except json.JSONDecodeError as e:
            error_response = {
                "jsonrpc": "2.0",
                "id": None,
                "error": {"code": -32700, "message": f"Parse error: {e}"}
            }
            print(json.dumps(error_response), flush=True)
        except Exception as e:
            error_response = {
                "jsonrpc": "2.0",
                "id": request_id,
                "error": {"code": -32603, "message": str(e)}
            }
            print(json.dumps(error_response), flush=True)


if __name__ == "__main__":
    router = MCPRouter()

    # Auto-register default server from env if specified
    default_server = os.environ.get("MCP_ROUTER_DEFAULT_SERVER")
    if default_server:
        router.register_server("default", default_server.split(), {})

    start_stdio_server(router)
