#!/usr/bin/env python3
"""
MCP Router - Passthrough router with response summarization.

Routes MCP requests to registered target servers, returns responses
with {summary, full} envelope where summary is Haiku-generated.

Usage:
    from mcp_router import MCPRouter, RouterResponse

    router = MCPRouter()
    router.register_server("serena", ["python", "-m", "serena"], {"tool_prefix": "serena"})
    response = router.route("serena", "find_symbol", {"name": "MyClass"})
    print(response.summary)  # Haiku-generated summary
    print(response.full)     # Full response (access only if needed)
"""

import hashlib
import json
import os
import subprocess
import sys
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timezone
import socket
from threading import Lock, RLock, Thread
import select
from pathlib import Path
from typing import Any, Callable, Optional, TYPE_CHECKING


def _router_log(component: str, message: str, level: str = "INFO") -> None:
    """Write a log entry with timestamp to router log file.

    Args:
        component: Component name (e.g., "socket", "route", "backend")
        message: The log message
        level: Log level (INFO, DEBUG, ERROR, WARN)
    """
    log_file = Path(__file__).parent.parent / ".state" / "router.log"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
    pid = os.getpid()

    # Ensure parent directory exists
    log_file.parent.mkdir(parents=True, exist_ok=True)

    with open(log_file, "a") as f:
        f.write(f"[{timestamp}] [{level}] [PID:{pid}] [{component}] {message}\n")

if TYPE_CHECKING:
    from lib.telemetry_service import TelemetryService

try:
    import anthropic

    ANTHROPIC_AVAILABLE = True
except ImportError:
    anthropic = None  # type: ignore
    ANTHROPIC_AVAILABLE = False

try:
    import openai
    OPENAI_AVAILABLE = True
except ImportError:
    openai = None  # type: ignore
    OPENAI_AVAILABLE = False

# Import v2 telemetry schema functions (optional - deprecated)
try:
    from telemetry_schema_v2 import (
        TelemetryV2,
        load_telemetry_v2,
        save_telemetry_v2,
        ensure_day,
        update_timing_stats,
    )
    TELEMETRY_V2_AVAILABLE = True
except ImportError:
    TELEMETRY_V2_AVAILABLE = False
    TelemetryV2 = dict  # type: ignore
    def load_telemetry_v2(path): return {}  # type: ignore
    def save_telemetry_v2(data, path): pass  # type: ignore
    def ensure_day(data, key): return data.setdefault(key, {})  # type: ignore
    def update_timing_stats(timing, backend, duration): pass  # type: ignore


@dataclass
class RouterResponse:
    """Response envelope with summary and full response.

    The summary is generated by Haiku and should be sufficient for most cases.
    Access .full only when you need the complete response data.
    """
    summary: str
    full: Any
    correlation_id: str = ""

    def __repr__(self):
        return (
            f"RouterResponse(\n"
            f"  summary={self.summary!r},\n"
            f"  full=<available - access only if needed>,\n"
            f"  correlation_id={self.correlation_id!r}\n"
            f")"
        )

    def __str__(self):
        return (
            f"Summary: {self.summary}\n"
            f"[Full response available via .full - access only if needed]"
        )


@dataclass
class ServerConfig:
    """Configuration for a registered MCP server."""
    name: str
    command: list[str]
    args: dict = field(default_factory=dict)
    tool_prefix: str = ""
    registered_at: str = ""

    def __post_init__(self):
        if not self.registered_at:
            self.registered_at = datetime.now(timezone.utc).isoformat()


@dataclass
class TelemetryEvent:
    """Single telemetry event."""
    timestamp: str
    tool: str
    backend: str
    duration_ms: int
    status: str  # "success" | "error"
    tokens_est: int = 0
    subagent_type: str = ""
    error_msg: str = ""


class TelemetryCollector:
    """Real-time telemetry collection for MCP router using v2 schema.

    Tracks all tool calls, durations, token estimates, and errors.
    Writes to telemetry.json on every event for real-time dashboard updates.
    Uses the unified v2 telemetry schema.
    """

    # Token estimates by tool type (conservative estimates)
    TOKEN_ESTIMATES = {
        "read_file": 2000,
        "find_symbol": 1500,
        "search_for_pattern": 1500,
        "get_symbols_overview": 1000,
        "list_dir": 500,
        "find_file": 500,
        "replace_content": 800,
        "replace_symbol_body": 1000,
        "insert_after_symbol": 800,
        "insert_before_symbol": 800,
        "execute_shell_command": 1000,
    }

    # Subagent token estimates (much larger)
    SUBAGENT_TOKEN_ESTIMATES = {
        "Explore": 25000,
        "Plan": 30000,
        "Implement": 100000,
        "general-purpose": 50000,
        "Bash": 10000,
        "feature-dev:code-explorer": 40000,
        "feature-dev:code-reviewer": 30000,
        "feature-dev:code-architect": 50000,
    }

    def __init__(
        self,
        telemetry_file: Optional[Path] = None,
        max_events: int = 500,
        telemetry_service: Optional['TelemetryService'] = None
    ):
        """Initialize telemetry collector.

        Args:
            telemetry_file: Path to write telemetry JSON
            max_events: Maximum events to keep (rolling window)
            telemetry_service: Optional TelemetryService for DuckDB persistence
        """
        self._telemetry_file = telemetry_file or Path.home() / ".claude/plugins/agent-swarm/.state/telemetry.json"
        self._max_events = max_events
        self._telemetry_service = telemetry_service
        self._lock = Lock()
        self._pending_requests: dict[str, tuple[str, str, dict, float]] = {}
        self._session_id = datetime.now(timezone.utc).isoformat()
        self._events: list[dict] = []  # Session events (rolling window)
        self._data: TelemetryV2 = load_telemetry_v2(self._telemetry_file)

    def _save(self) -> None:
        """Save telemetry to file using v2 schema."""
        save_telemetry_v2(self._data, self._telemetry_file)

    def _estimate_tokens(self, tool: str, subagent_type: str = "") -> int:
        """Estimate tokens for a tool call."""
        if subagent_type:
            return self.SUBAGENT_TOKEN_ESTIMATES.get(subagent_type, 50000)
        base_tool = tool.split("__")[-1] if "__" in tool else tool
        return self.TOKEN_ESTIMATES.get(base_tool, 500)

    def _get_today_key(self) -> str:
        """Get today's date key in YYYY-MM-DD format."""
        return datetime.now(timezone.utc).strftime("%Y-%m-%d")

    def track_request(self, destination: str, tool_name: str, args: dict) -> str:
        """Called when a request is made. Returns correlation_id."""
        import time
        correlation_id = f"req-{int(time.time() * 1000)}-{hash((destination, tool_name)) & 0xFFFF:04x}"

        with self._lock:
            self._pending_requests[correlation_id] = (
                tool_name, destination, args, time.time()
            )
        return correlation_id

    def track_response(
        self,
        correlation_id: str,
        error: bool = False,
        error_msg: str = "",
        full_size: int = 0,
        summary_size: int = 0
    ) -> None:
        """Called when a response is received.

        Args:
            correlation_id: Request correlation ID
            error: Whether the request errored
            error_msg: Error message if any
            full_size: Size of full response in chars (for efficiency tracking)
            summary_size: Size of summary in chars (for efficiency tracking)
        """
        import time

        with self._lock:
            if correlation_id not in self._pending_requests:
                return

            tool_name, backend, args, start_time = self._pending_requests.pop(correlation_id)
            duration_ms = int((time.time() - start_time) * 1000)

            # Check for subagent
            subagent_type = args.get("subagent_type", "") if tool_name == "Task" else ""
            tokens_est = self._estimate_tokens(tool_name, subagent_type)

            # Create event for session tracking
            event = {
                "ts": datetime.now(timezone.utc).isoformat(),
                "tool": tool_name,
                "backend": backend,
                "duration_ms": duration_ms,
                "status": "error" if error else "success",
                "tokens_est": tokens_est,
                "subagent_type": subagent_type,
                "error_msg": error_msg[:200] if error_msg else "",
                "full_size": full_size,
                "summary_size": summary_size
            }

            # Add to session events (rolling window)
            self._events.append(event)
            if len(self._events) > self._max_events:
                self._events = self._events[-self._max_events:]

            # Update v2 telemetry
            self._update_v2_telemetry(event, error, full_size, summary_size, duration_ms)

            # Send to TelemetryService if available (dual-write during migration)
            if self._telemetry_service:
                self._send_to_service(event, error_msg)

            # Save immediately for real-time updates
            self._save()

    def _update_v2_telemetry(
        self,
        event: dict,
        error: bool,
        full_size: int,
        summary_size: int,
        duration_ms: int
    ) -> None:
        """Update v2 telemetry structure."""
        day_key = self._get_today_key()
        day_data = ensure_day(self._data, day_key)

        # Update call counts
        calls = day_data.setdefault("calls", {"total": 0, "by_tool": {}, "by_backend": {}})
        calls["total"] = calls.get("total", 0) + 1

        tool = event["tool"]
        calls.setdefault("by_tool", {})[tool] = calls.get("by_tool", {}).get(tool, 0) + 1

        backend = event["backend"]
        calls.setdefault("by_backend", {})[backend] = calls.get("by_backend", {}).get(backend, 0) + 1

        # Update timing stats
        timing = day_data.setdefault("timing", {"avg_response_ms": 0.0, "p95_response_ms": 0.0, "by_backend": {}})
        update_timing_stats(timing, backend, duration_ms)

        # Update summarization stats if applicable
        if full_size > 0 and summary_size > 0:
            summ = day_data.setdefault("summarization", {
                "offered": 0, "accepted": 0, "rejected": 0,
                "acceptance_rate": 0.0, "tokens_saved_est": 0
            })
            summ["offered"] = summ.get("offered", 0) + 1
            summ["accepted"] = summ.get("accepted", 0) + 1  # Router always accepts
            chars_saved = full_size - summary_size
            tokens_saved = chars_saved // 4  # ~4 chars per token
            summ["tokens_saved_est"] = summ.get("tokens_saved_est", 0) + tokens_saved
            total = summ.get("offered", 1)
            summ["acceptance_rate"] = summ.get("accepted", 0) / total if total > 0 else 0.0

        # Track session
        sessions = day_data.setdefault("sessions", [])
        if self._session_id not in sessions:
            sessions.append(self._session_id)

    def _send_to_service(self, event: dict, error_msg: str) -> None:
        """Send event to TelemetryService for DuckDB persistence.
        
        Maps TelemetryCollector event format to TelemetryService expected format.
        
        Args:
            event: Event dict from track_response
            error_msg: Error message if error occurred
        """
        # Map TelemetryCollector fields to TelemetryService/DuckDB schema
        service_event = {
            "timestamp": event["ts"],  # ts -> timestamp
            "session_id": self._session_id,
            "tool": event["tool"],
            "backend": event["backend"],
            "duration_ms": event["duration_ms"],
            "status": event["status"],
        }
        
        # Add optional fields
        if event.get("subagent_type"):
            service_event["agent_type"] = event["subagent_type"]  # subagent_type -> agent_type
        
        # Add error type if error occurred
        if event["status"] == "error" and error_msg:
            # Extract error type from message (simple heuristic)
            service_event["error_type"] = error_msg.split(":")[0] if ":" in error_msg else "Error"
        
        # Add summarization fields if applicable
        if event.get("full_size", 0) > 0 and event.get("summary_size", 0) > 0:
            service_event["was_summarized"] = True
            service_event["original_size"] = event["full_size"]
            service_event["summary_size"] = event["summary_size"]
        
        # Send to service
        try:
            self._telemetry_service.insert_event(service_event)
        except Exception:
            # Don't let telemetry failures break routing
            pass

    def get_summary(self) -> dict:
        """Get current telemetry summary."""
        with self._lock:
            day_key = self._get_today_key()
            day_data = self._data.get("days", {}).get(day_key, {})

            calls = day_data.get("calls", {})
            timing = day_data.get("timing", {})
            summ = day_data.get("summarization", {})

            # Compute efficiency metrics from summarization data
            tokens_saved = summ.get("tokens_saved_est", 0)
            offered = summ.get("offered", 0)
            
            # Get socket events if tracked
            socket_events = getattr(self, '_socket_events', [])
            socket_summary = {}
            if socket_events:
                # Count by status
                by_status = {}
                total_duration = 0
                for evt in socket_events:
                    status = evt.get("status", "unknown")
                    by_status[status] = by_status.get(status, 0) + 1
                    total_duration += evt.get("duration_ms", 0)
                socket_summary = {
                    "total": len(socket_events),
                    "by_status": by_status,
                    "avg_duration_ms": total_duration // len(socket_events) if socket_events else 0,
                    "recent": socket_events[-5:]  # Last 5 socket events
                }

            return {
                "session_id": self._session_id,
                "event_count": len(self._events),
                "today": day_key,
                "aggregates": {
                    "by_tool": calls.get("by_tool", {}),
                    "by_backend": calls.get("by_backend", {}),
                    "totals": {"calls": calls.get("total", 0)},
                    "timing": timing,
                    "efficiency": {
                        "calls_summarized": offered,
                        "tokens_saved_est": tokens_saved,
                    }
                },
                "socket": socket_summary,
                "recent_events": self._events[-10:]  # Last 10
            }




class MCPRouter:
    """Thread-safe MCP request router with backpressure handling.

    Routes requests to registered target servers, summarizes responses,
    and returns {summary, full} envelope.

    Connections are spawned on first use and kept alive for reuse.
    Per-backend locks ensure safe concurrent access.

    Summarizer options:
        - "openai": Use OpenAI API (requires OPENAI_API_KEY)
        - "anthropic": Use Anthropic API (requires ANTHROPIC_API_KEY)
        - "none": Use fallback heuristics only

    Hook points:
        on_request: Called before forwarding (destination, tool, args)
        on_response: Called after response packaged (RouterResponse)
    """

    # Default models for each provider
    DEFAULT_MODELS = {
        "openai": "gpt-4o-mini",
        "anthropic": "claude-3-5-haiku-20241022",
    }

    def __init__(
        self,
        max_queue_size: int = 1000,
        summarizer: str = "auto",
        summarizer_model: Optional[str] = None,
        enable_telemetry: bool = True,
    ):
        """Initialize router with request queue and lock.

        Args:
            max_queue_size: Maximum pending requests before blocking.
            summarizer: Provider for summarization ("auto", "openai", "anthropic", "none").
                        "auto" tries openai first, then anthropic, then falls back.
            summarizer_model: Model to use (defaults based on provider).
            enable_telemetry: Enable real-time telemetry collection.
        """
        self._queue: deque = deque(maxlen=max_queue_size)
        self._lock = Lock()
        self._servers: dict[str, ServerConfig] = {}
        self._connections: dict[str, subprocess.Popen] = {}  # Live backend processes
        self._backend_locks: dict[str, RLock] = {}  # Per-backend locks

        # Shadow cache for workflow state (survives backend respawns)
        self._workflow_state_cache: dict[str, dict] = {}
        # Counter for generating unique content IDs
        self._content_id_counter = 0
        # Storage for content that can be retrieved by ID (for two-step content retrieval)
        self._content_store: dict[str, Any] = {}

        # Initialize summarizer (decide provider once at startup)
        self._llm_call: Callable[[str], str] = self._init_summarizer(summarizer, summarizer_model)

        # Hook points for extensibility (logging, telemetry, testing)
        self.on_request: list[Callable[[str, str, dict], None]] = []
        self.on_response: list[Callable[[RouterResponse], None]] = []

        # Event system for async tool execution
        self._event_queue: dict[str, list[dict]] = {}  # topic -> events
        self._event_responses: dict[str, dict] = {}  # correlation_id -> response
        self._event_lock = Lock()

        # Telemetry collector for real-time metrics
        self.telemetry: Optional[TelemetryCollector] = TelemetryCollector() if enable_telemetry else None

        # Socket listener for external clients (hooks, CLIs)
        self._socket_server: Optional[socket.socket] = None
        self._socket_thread: Optional[Thread] = None
        self._socket_port: int = 0
        self._socket_running: bool = False
        self._port_file = Path(__file__).parent.parent / ".state" / "router.port"

        # Federation state
        self._is_primary: bool = False  # True if we own the socket listener
        self._main_router_port: int = 0  # Port of main router (if we're secondary)

    def _cache_workflow_state(self, tool_name: str, args: dict, response: dict) -> None:
        """Cache workflow state from set/update/start operations."""
        if tool_name == "workflow_set_state":
            workflow_id = args.get("workflow_id")
            state = args.get("state")
            if workflow_id and state:
                self._workflow_state_cache[workflow_id] = state
        elif tool_name == "workflow_start":
            workflow_id = args.get("workflow_id")
            state = args.get("initial_state")
            if workflow_id and state:
                self._workflow_state_cache[workflow_id] = state
        elif tool_name == "workflow_stop":
            workflow_id = args.get("workflow_id")
            if workflow_id:
                self._workflow_state_cache.pop(workflow_id, None)

    def _restore_workflow_state(self, server_name: str) -> None:
        """Restore cached workflow state to a freshly spawned backend."""
        if server_name != "workflow" or not self._workflow_state_cache:
            return
        # Restore each cached workflow
        server = self._servers.get(server_name)
        if not server:
            return
        for workflow_id, state in self._workflow_state_cache.items():
            try:
                self._forward_to_server(server, "workflow_set_state", {
                    "workflow_id": workflow_id,
                    "state": state
                }, _is_restore=True)
            except Exception:
                pass  # Best effort  # Best effort

    def clear_workflow_cache(self, workflow_id: str | None = None) -> dict:
        """Clear cached workflow state.
        
        Args:
            workflow_id: Specific workflow to clear, or None for all.
            
        Returns:
            Dict with cleared workflow IDs.
        """
        if workflow_id:
            existed = self._workflow_state_cache.pop(workflow_id, None) is not None
            return {"cleared": [workflow_id] if existed else [], "all": False}
        else:
            cleared = list(self._workflow_state_cache.keys())
            self._workflow_state_cache.clear()
            return {"cleared": cleared, "all": True}

    def _init_summarizer(
        self,
        provider: str,
        model: Optional[str]
    ) -> Callable[[str], str]:
        """Initialize summarizer and return the LLM call function.

        Decides provider at startup, returns a simple prompt->response function.
        """
        # Auto-detect: try openai, then anthropic
        if provider == "auto":
            if OPENAI_AVAILABLE and os.environ.get("OPENAI_API_KEY"):
                provider = "openai"
            elif ANTHROPIC_AVAILABLE and os.environ.get("ANTHROPIC_API_KEY"):
                provider = "anthropic"
            else:
                provider = "none"

        if provider == "openai":
            return self._init_openai(model or self.DEFAULT_MODELS["openai"])
        elif provider == "anthropic":
            return self._init_anthropic(model or self.DEFAULT_MODELS["anthropic"])
        else:
            return lambda prompt: ""  # Empty = use fallback

    def _init_openai(self, model: str) -> Callable[[str], str]:
        """Initialize OpenAI client and return call function."""
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key or not OPENAI_AVAILABLE:
            return lambda prompt: ""

        client = openai.OpenAI(api_key=api_key)

        def call(prompt: str) -> str:
            try:
                response = client.chat.completions.create(
                    model=model,
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=500,
                    temperature=0,
                )
                return response.choices[0].message.content.strip()
            except Exception:
                return ""

        return call

    def _init_anthropic(self, model: str) -> Callable[[str], str]:
        """Initialize Anthropic client and return call function."""
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key or not ANTHROPIC_AVAILABLE:
            return lambda prompt: ""

        client = anthropic.Anthropic(api_key=api_key)

        def call(prompt: str) -> str:
            try:
                response = client.messages.create(
                    model=model,
                    max_tokens=500,
                    temperature=0,
                    messages=[{"role": "user", "content": prompt}],
                )
                return response.content[0].text.strip()
            except Exception:
                return ""

        return call

    # === Registration API ===

    def register_server(
        self,
        name: str,
        command: list[str],
        args: Optional[dict] = None,
        tool_prefix: str = ""
    ) -> dict:
        """Register an MCP server for routing.

        Args:
            name: Unique server identifier
            command: Subprocess command to spawn server
            args: Optional initialization arguments
            tool_prefix: Prefix for tool names from this server

        Returns:
            Registration confirmation dict
        """
        with self._lock:
            config = ServerConfig(
                name=name,
                command=command,
                args=args or {},
                tool_prefix=tool_prefix
            )
            self._servers[name] = config

            return {
                "status": "registered",
                "name": name,
                "tool_prefix": tool_prefix,
                "registered_at": config.registered_at
            }

    def unregister_server(self, name: str) -> dict:
        """Remove a registered server.

        Args:
            name: Server identifier to remove

        Returns:
            Confirmation dict
        """
        with self._lock:
            existed = self._servers.pop(name, None) is not None
            # Kill connection if exists
            proc = self._connections.pop(name, None)
            if proc:
                proc.terminate()
            return {
                "status": "unregistered" if existed else "not_found",
                "name": name
            }

    def shutdown(self) -> None:
        """Shutdown all backend connections and socket listener."""
        # Stop socket listener first
        self.stop_socket_listener()

        with self._lock:
            for _, proc in list(self._connections.items()):
                try:
                    proc.terminate()
                    proc.wait(timeout=5)
                except Exception:
                    proc.kill()
            self._connections.clear()

    # ─────────────────────────────────────────────────────────────
    # Socket Listener for External Clients
    # ─────────────────────────────────────────────────────────────

    def start_socket_listener(self, port: int = 0, force_primary: bool = False) -> int:
        """Start socket listener with federation support.

        Checks for existing main router first. If one exists and is responsive,
        this router becomes secondary and proxies requests to the main.
        Otherwise, this router becomes primary.

        Args:
            port: Port to listen on (0 for auto-assign).
            force_primary: If True, always try to become primary (for testing).

        Returns:
            The actual port being used (main router's port if secondary).
        """
        # Federation check: is there already a main router?
        if not force_primary:
            main_port = self._check_main_router()
            if main_port:
                # Become secondary - proxy to main router
                self._is_primary = False
                self._main_router_port = main_port
                self._socket_port = main_port  # Report main's port
                _router_log("federation", f"Joined as secondary, main router on port {main_port}")
                return main_port

        # Try to become primary
        max_retries = 3
        for attempt in range(max_retries):
            try:
                self._socket_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                self._socket_server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                self._socket_server.bind(("127.0.0.1", port))
                self._socket_server.listen(5)
                self._socket_port = self._socket_server.getsockname()[1]
                self._socket_running = True
                self._is_primary = True

                # Write port to file for client/secondary discovery
                self._port_file.parent.mkdir(parents=True, exist_ok=True)
                self._port_file.write_text(str(self._socket_port))

                # Start accept loop in background thread
                self._socket_thread = Thread(target=self._socket_accept_loop, daemon=True)
                self._socket_thread.start()

                _router_log("federation", f"Started as PRIMARY on port {self._socket_port}")
                return self._socket_port

            except OSError as e:
                # Port binding failed - likely race condition
                if e.errno == 98:  # EADDRINUSE
                    _router_log("federation", f"Bind failed (attempt {attempt + 1}), checking for main router")
                    if self._socket_server:
                        self._socket_server.close()
                        self._socket_server = None

                    # Another router might have just started - check again
                    import time
                    time.sleep(0.1 * (attempt + 1))  # Backoff
                    main_port = self._check_main_router()
                    if main_port:
                        self._is_primary = False
                        self._main_router_port = main_port
                        self._socket_port = main_port
                        _router_log("federation", f"Lost race, joined as secondary on port {main_port}")
                        return main_port
                else:
                    raise

        # All retries failed
        raise RuntimeError("Failed to start socket listener after retries")

    def stop_socket_listener(self) -> None:
        """Stop socket listener and clean up port file."""
        self._socket_running = False
        if self._socket_server:
            try:
                self._socket_server.close()
            except Exception:
                pass
        # Only delete port file if we're the primary (we created it)
        if self._is_primary and self._port_file.exists():
            try:
                self._port_file.unlink()
            except Exception:
                pass

    # ─────────────────────────────────────────────────────────────
    # Federation - Multiple Router Coordination
    # ─────────────────────────────────────────────────────────────

    def _check_main_router(self) -> Optional[int]:
        """Check if a main router exists and is responsive.

        Returns:
            Port of main router if alive, None otherwise.
        """
        if not self._port_file.exists():
            return None

        try:
            port = int(self._port_file.read_text().strip())
            # Try to connect and ping
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(2.0)
            sock.connect(("127.0.0.1", port))

            # Send ping request
            request = {
                "jsonrpc": "2.0",
                "id": 1,
                "method": "tools/call",
                "params": {"name": "router__ping", "arguments": {}}
            }
            sock.sendall(json.dumps(request).encode() + b"\n")

            # Wait for response
            response_data = b""
            while b"\n" not in response_data:
                chunk = sock.recv(4096)
                if not chunk:
                    break
                response_data += chunk

            sock.close()

            if response_data:
                response = json.loads(response_data.decode().strip())
                if "result" in response:
                    _router_log("federation", f"Main router alive on port {port}")
                    return port
        except (socket.error, json.JSONDecodeError, ValueError) as e:
            _router_log("federation", f"Main router check failed: {e}", "DEBUG")
        except Exception as e:
            _router_log("federation", f"Unexpected error checking main router: {e}", "WARN")

        return None

    def _proxy_to_main(self, request: dict) -> dict:
        """Proxy a request to the main router.

        Args:
            request: JSON-RPC request to forward.

        Returns:
            Response from main router.
        """
        if not self._main_router_port:
            return {"error": {"code": -32603, "message": "No main router configured"}}

        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(30.0)
            sock.connect(("127.0.0.1", self._main_router_port))

            # Send request
            sock.sendall(json.dumps(request).encode() + b"\n")

            # Receive response
            response_data = b""
            while b"\n" not in response_data:
                chunk = sock.recv(8192)
                if not chunk:
                    break
                response_data += chunk

            sock.close()

            if response_data:
                return json.loads(response_data.decode().strip())
            return {"error": {"code": -32603, "message": "Empty response from main router"}}

        except socket.timeout:
            _router_log("federation", "Proxy timeout to main router", "ERROR")
            return {"error": {"code": -32603, "message": "Timeout proxying to main router"}}
        except Exception as e:
            _router_log("federation", f"Proxy error: {e}", "ERROR")
            return {"error": {"code": -32603, "message": f"Proxy error: {e}"}}

    def is_primary(self) -> bool:
        """Check if this router is the primary (owns socket listener)."""
        return self._is_primary

    def _socket_accept_loop(self) -> None:
        """Accept connections and spawn handler threads."""
        self._active_socket_connections = 0
        self._total_socket_accepts = 0
        _router_log("socket", f"Accept loop started on port {self._socket_port}")

        while self._socket_running:
            try:
                self._socket_server.settimeout(1.0)  # Check running flag periodically
                try:
                    client, addr = self._socket_server.accept()
                    self._total_socket_accepts += 1
                    self._active_socket_connections += 1
                    conn_id = self._total_socket_accepts
                    _router_log("socket", f"ACCEPT conn_id={conn_id} from={addr} active={self._active_socket_connections}")

                    # Wrap handler to track connection lifecycle
                    def handle_and_track(c, cid):
                        try:
                            self._handle_socket_client(c, cid)
                        finally:
                            self._active_socket_connections -= 1
                            _router_log("socket", f"CLOSE conn_id={cid} active={self._active_socket_connections}")

                    Thread(
                        target=handle_and_track,
                        args=(client, conn_id),
                        daemon=True
                    ).start()
                except socket.timeout:
                    continue
            except Exception as e:
                if self._socket_running:
                    _router_log("socket", f"Accept error: {e}", "ERROR")
                    continue
                break
        _router_log("socket", "Accept loop stopped")

    def _handle_socket_client(self, client: socket.socket, conn_id: int = 0) -> None:
        """Handle a single client connection.

        Reads JSON-RPC request, routes it, sends response.
        Connection is closed after one request-response cycle.
        """
        import time
        start_time = time.time()
        tool_name = "unknown"
        log_prefix = f"conn_id={conn_id}"

        try:
            # Set timeout on socket operations
            client.settimeout(30.0)  # 30 second timeout for reads
            _router_log("socket", f"{log_prefix} Reading request...")

            # Read request (newline-delimited JSON)
            data = b""
            while b"\n" not in data:
                chunk = client.recv(4096)
                if not chunk:
                    _router_log("socket", f"{log_prefix} Client disconnected before sending data", "WARN")
                    return
                data += chunk

            read_time = time.time()
            _router_log("socket", f"{log_prefix} Received {len(data)} bytes in {int((read_time - start_time) * 1000)}ms")

            request = json.loads(data.decode().strip())
            request_id = request.get("id")
            method = request.get("method", "")
            params = request.get("params", {})
            _router_log("socket", f"{log_prefix} Parsed request: method={method} id={request_id}")

            # Route the request (same logic as stdio)
            if method == "tools/list":
                # Return all available tools from all backends
                tools = self._list_all_tools_for_socket()
                result = {"tools": tools}
                response = {
                    "jsonrpc": "2.0",
                    "id": request_id,
                    "result": result
                }
                response_bytes = json.dumps(response).encode() + b"\n"
                client.sendall(response_bytes)
                duration_ms = int((time.time() - start_time) * 1000)
                _router_log("socket", f"{log_prefix} COMPLETE tools/list duration={duration_ms}ms tools_count={len(tools)}")
                return

            elif method == "tools/call":
                tool_name = params.get("name", "")
                args = params.get("arguments", {})
                _router_log("socket", f"{log_prefix} ROUTE tool={tool_name} args_keys={list(args.keys())}")

                # Handle router built-in tools first
                if tool_name == "router__ping":
                    result = {"content": [{"type": "text", "text": "pong! Router is working."}]}
                elif tool_name == "router__telemetry":
                    if self.telemetry:
                        summary = self.telemetry.get_summary()
                        summary["socket_stats"] = self.get_socket_stats()
                        summary["federation"] = {"is_primary": self._is_primary, "main_port": self._main_router_port}
                        result = {"content": [{"type": "text", "text": json.dumps(summary, indent=2)}]}
                    else:
                        result = {"content": [{"type": "text", "text": "Telemetry not enabled"}]}
                elif tool_name == "router__list_tools":
                    tools = self._list_all_tools_for_socket()
                    result = {"content": [{"type": "text", "text": json.dumps({"tools": [t["name"] for t in tools]}, indent=2)}]}
                elif "__" in tool_name:
                    prefix, actual_tool = tool_name.split("__", 1)
                    # Find backend by prefix
                    destination = None
                    for server in self.list_servers():
                        if server.get("tool_prefix") == prefix or server["name"] == prefix:
                            destination = server["name"]
                            break

                    if not destination:
                        _router_log("socket", f"{log_prefix} Unknown backend prefix: {prefix}", "ERROR")
                        result = {"content": [{"type": "text", "text": f"Error: Unknown backend prefix: {prefix}"}], "isError": True}
                    else:
                        _router_log("socket", f"{log_prefix} Routing to backend={destination} tool={actual_tool}")
                        _route_start = time.time()  # noqa: F841 - kept for future duration logging
                        response = self.route(destination, actual_tool, args)
                        route_duration = int((time.time() - _route_start) * 1000)
                        _router_log("socket", f"{log_prefix} Backend responded in {route_duration}ms")

                        backend_result = response.full
                        if isinstance(backend_result, dict) and "error" in backend_result:
                            _router_log("socket", f"{log_prefix} Backend error: {str(backend_result.get('error', ''))[:100]}", "ERROR")
                            result = {"content": [{"type": "text", "text": f"Error: {backend_result['error']}"}], "isError": True}
                        else:
                            if isinstance(backend_result, dict) and "result" in backend_result:
                                full_content = backend_result["result"]
                            else:
                                full_content = backend_result
                            result = full_content
                            result_size = len(json.dumps(result)) if result else 0
                            _router_log("socket", f"{log_prefix} Success result_size={result_size}")
                else:
                    _router_log("socket", f"{log_prefix} Tool name not prefixed: {tool_name}", "ERROR")
                    result = {"content": [{"type": "text", "text": "Tool name must be prefixed: prefix__tool"}], "isError": True}
            else:
                _router_log("socket", f"{log_prefix} Unsupported method: {method}", "WARN")
                result = {"error": f"Unsupported method: {method}"}

            # Send response
            response = {
                "jsonrpc": "2.0",
                "id": request_id,
                "result": result
            }
            response_bytes = json.dumps(response).encode() + b"\n"
            client.sendall(response_bytes)

            # Track successful socket request in telemetry
            duration_ms = int((time.time() - start_time) * 1000)
            _router_log("socket", f"{log_prefix} COMPLETE tool={tool_name} duration={duration_ms}ms response_size={len(response_bytes)}")
            if self.telemetry:
                self._track_socket_event("success", tool_name, duration_ms)

        except socket.timeout:
            duration_ms = int((time.time() - start_time) * 1000)
            _router_log("socket", f"{log_prefix} TIMEOUT tool={tool_name} duration={duration_ms}ms", "ERROR")
            if self.telemetry:
                self._track_socket_event("timeout", tool_name, duration_ms)
            try:
                error_response = {
                    "jsonrpc": "2.0",
                    "id": None,
                    "error": {"code": -32603, "message": "Socket timeout"}
                }
                client.sendall(json.dumps(error_response).encode() + b"\n")
            except Exception:
                pass
        except Exception as e:
            duration_ms = int((time.time() - start_time) * 1000)
            _router_log("socket", f"{log_prefix} ERROR tool={tool_name} duration={duration_ms}ms error={str(e)[:100]}", "ERROR")
            if self.telemetry:
                self._track_socket_event("error", tool_name, duration_ms, str(e)[:100])
            try:
                error_response = {
                    "jsonrpc": "2.0",
                    "id": None,
                    "error": {"code": -32603, "message": str(e)}
                }
                client.sendall(json.dumps(error_response).encode() + b"\n")
            except Exception:
                pass
        finally:
            try:
                client.close()
            except Exception:
                pass

    def _track_socket_event(
        self,
        status: str,
        tool_name: str,
        duration_ms: int,
        error_msg: str = ""
    ) -> None:
        """Track socket connection event in telemetry.
        
        Args:
            status: "success", "timeout", or "error"
            tool_name: Tool that was called
            duration_ms: Request duration in milliseconds
            error_msg: Error message if any
        """
        if not self.telemetry:
            return
            
        # Add to telemetry data under socket_events
        with self.telemetry._lock:
            if not hasattr(self.telemetry, '_socket_events'):
                self.telemetry._socket_events = []
            
            event = {
                "ts": datetime.now(timezone.utc).isoformat(),
                "status": status,
                "tool": tool_name,
                "duration_ms": duration_ms,
                "error_msg": error_msg
            }
            self.telemetry._socket_events.append(event)
            
            # Keep last 100 events
            if len(self.telemetry._socket_events) > 100:
                self.telemetry._socket_events = self.telemetry._socket_events[-100:]

    def store_content(self, content: Any) -> str:
        """Store content and return a unique content_id."""
        self._content_id_counter += 1
        content_id = f"content_{self._content_id_counter}"
        self._content_store[content_id] = content
        return content_id

    def get_full_content(self, content_id: str) -> dict:
        """Retrieve stored content by ID. Returns error dict if not found."""
        if content_id in self._content_store:
            content = self._content_store.pop(content_id)  # Remove after retrieval (one-time use)
            return {"content": content}
        return {"error": f"Content not found for ID: {content_id}"}

    def get_socket_stats(self) -> dict:
        """Get current socket connection statistics.
        
        Returns:
            Dict with active connections, total accepts, and event summary
        """
        active = getattr(self, '_active_socket_connections', 0)
        total = getattr(self, '_total_socket_accepts', 0)
        
        socket_events = []
        if self.telemetry:
            socket_events = getattr(self.telemetry, '_socket_events', [])
        
        # Count by status
        by_status = {}
        for evt in socket_events:
            status = evt.get("status", "unknown")
            by_status[status] = by_status.get(status, 0) + 1
        
        return {
            "active_connections": active,
            "total_accepts": total,
            "events_tracked": len(socket_events),
            "by_status": by_status,
            "recent_events": socket_events[-10:] if socket_events else []
        }

    def list_servers(self) -> list[dict]:
        """List all registered servers.

        Returns:
            List of server info dicts
        """
        with self._lock:
            return [
                {
                    "name": s.name,
                    "command": s.command,
                    "tool_prefix": s.tool_prefix,
                    "registered_at": s.registered_at
                }
                for s in self._servers.values()
            ]

    # ==================== Event System ====================

    def event_publish(self, topic: str, data: dict, correlation_id: str) -> dict:
        """Publish event to internal event bus."""
        with self._event_lock:
            if topic not in self._event_queue:
                self._event_queue[topic] = []
            event = {
                "topic": topic,
                "data": data,
                "correlation_id": correlation_id,
                "timestamp": datetime.now(timezone.utc).isoformat()
            }
            self._event_queue[topic].append(event)
            _router_log("event", f"PUBLISH topic={topic} cid={correlation_id}")
            return {"status": "published", "correlation_id": correlation_id}

    def event_poll(self, correlation_id: str, timeout_ms: int = 0) -> Optional[dict]:
        """Poll for response by correlation ID."""
        with self._event_lock:
            response = self._event_responses.pop(correlation_id, None)
            if response:
                _router_log("event", f"POLL cid={correlation_id} found")
            return response

    def event_respond(self, correlation_id: str, data: dict) -> None:
        """Store response for a correlation ID."""
        with self._event_lock:
            self._event_responses[correlation_id] = data
            _router_log("event", f"RESPOND cid={correlation_id}")

    def _list_all_tools_for_socket(self) -> list[dict]:
        """Get all tools from all backends for socket clients.

        Returns:
            List of tool definitions with prefixed names.
        """
        # Router's own tools
        all_tools = [
            {
                "name": "router__ping",
                "description": "Test tool that returns a simple message",
                "inputSchema": {"type": "object", "properties": {}},
            },
            {
                "name": "router__telemetry",
                "description": "Get real-time telemetry data",
                "inputSchema": {"type": "object", "properties": {}},
            },
            {
                "name": "router__telemetry_analysis",
                "description": "Get analysis of token usage trends",
                "inputSchema": {"type": "object", "properties": {}},
            },
            # Event system pseudo-tools (handled by hooks, not router)
            {
                "name": "router__request",
                "description": "Async tool request. Returns correlation_id. Poll router__poll for response.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "tool": {"type": "string", "description": "Tool name (e.g., serena__find_symbol)"},
                        "args": {"type": "object", "description": "Tool arguments"}
                    },
                    "required": ["tool", "args"]
                }
            },
            {
                "name": "router__poll",
                "description": "Poll for async response by correlation_id.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "correlation_id": {"type": "string", "description": "Correlation ID from router__request"}
                    },
                    "required": ["correlation_id"]
                }
            },
            {
                "name": "router__publish",
                "description": "Publish event to topic.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "topic": {"type": "string", "description": "Event topic"},
                        "data": {"type": "object", "description": "Event data"}
                    },
                    "required": ["topic", "data"]
                }
            },
            {
                "name": "router__list_tools",
                "description": "List all available tools.",
                "inputSchema": {"type": "object", "properties": {}}
            },
        ]

        # Get tools from all backends
        for server in self.list_servers():
            name = server["name"]
            prefix = server.get("tool_prefix") or name

            try:
                response = self._forward_to_server(
                    self._servers[name],
                    "__list__",  # Special: triggers tools/list
                    {}
                )
                if "result" in response and "tools" in response["result"]:
                    for tool in response["result"]["tools"]:
                        # Prefix tool name
                        tool_copy = tool.copy()
                        tool_copy["name"] = f"{prefix}__{tool['name']}"
                        all_tools.append(tool_copy)
            except Exception:
                pass  # Skip failed backends

        return all_tools

    # === Routing ===

    def route(
        self,
        destination: str,
        tool_name: str,
        args: dict,
        skip_summary: bool = False
    ) -> RouterResponse:
        """Route a tool request to target server.

        Args:
            destination: Target server name
            tool_name: Tool to invoke
            args: Tool arguments
            skip_summary: If True, skip LLM summarization (faster for internal calls)

        Returns:
            RouterResponse with structured summary and full response
        """
        import time
        _route_start = time.time()  # noqa: F841 - kept for future duration logging
        correlation_id = self._generate_correlation_id(destination, tool_name, args)
        _router_log("route", f"ENTER dest={destination} tool={tool_name} corr_id={correlation_id}")

        # Start telemetry tracking
        telemetry_id = None
        if self.telemetry:
            telemetry_id = self.telemetry.track_request(destination, tool_name, args)

        # Fire request hooks
        for hook in self.on_request:
            try:
                hook(destination, tool_name, args)
            except Exception:
                pass  # Don't let hooks break routing

        # Federation: if secondary, proxy to main router
        if not self._is_primary and self._main_router_port:
            _router_log("route", f"PROXY to main router port {self._main_router_port}")
            proxy_request = {
                "jsonrpc": "2.0",
                "id": 1,
                "method": "tools/call",
                "params": {
                    "name": f"{destination}__{tool_name}",
                    "arguments": args
                }
            }
            proxy_response = self._proxy_to_main(proxy_request)

            # Extract result from proxy response
            if "error" in proxy_response:
                error_msg = str(proxy_response.get("error", {}).get("message", "Proxy error"))
                response = RouterResponse(
                    summary=f"Error: {error_msg}",
                    full={"error": error_msg},
                    correlation_id=correlation_id
                )
            else:
                result = proxy_response.get("result", {})
                # Parse the envelope if present
                if isinstance(result, dict) and "content" in result:
                    content = result.get("content", [])
                    if content and isinstance(content[0], dict):
                        text = content[0].get("text", "{}")
                        try:
                            envelope = json.loads(text)
                            response = RouterResponse(
                                summary=envelope.get("summary", ""),
                                full=envelope.get("full", result),
                                correlation_id=correlation_id
                            )
                        except json.JSONDecodeError:
                            response = RouterResponse(
                                summary=text[:200],
                                full=result,
                                correlation_id=correlation_id
                            )
                    else:
                        response = RouterResponse(
                            summary=str(result)[:200],
                            full=result,
                            correlation_id=correlation_id
                        )
                else:
                    response = RouterResponse(
                        summary=str(result)[:200],
                        full=result,
                        correlation_id=correlation_id
                    )

            # Complete telemetry
            if self.telemetry and telemetry_id:
                self.telemetry.track_response(
                    telemetry_id,
                    error="error" in proxy_response,
                    error_msg=str(proxy_response.get("error", ""))[:200]
                )

            # Fire response hooks
            for hook in self.on_response:
                try:
                    hook(response)
                except Exception:
                    pass

            return response

        # Get target server
        with self._lock:
            server = self._servers.get(destination)

        error = False
        error_msg = ""

        if not server:
            error = True
            error_msg = f"Server '{destination}' not registered"
            _router_log("route", f"ERROR server not registered: {destination}", "ERROR")
            response = RouterResponse(
                summary=f"Error: {error_msg}",
                full={"error": error_msg},
                correlation_id=correlation_id
            )
        else:
            # Forward request
            forward_start = time.time()
            full_response = self._forward_to_server(server, tool_name, args)
            forward_duration = int((time.time() - forward_start) * 1000)
            _router_log("route", f"Backend responded in {forward_duration}ms")

            # Check for error in response
            if isinstance(full_response, dict) and "error" in full_response:
                error = True
                error_msg = str(full_response.get("error", "Unknown error"))[:200]
                _router_log("route", f"Backend error: {error_msg}", "ERROR")

            # Generate structured summary using schema extraction (skip for internal calls)
            if skip_summary:
                summary = json.dumps({"skipped": True})
            else:
                summary = self._extract_summary(tool_name, full_response)

            response = RouterResponse(
                summary=summary,
                full=full_response,
                correlation_id=correlation_id
            )

        # Calculate sizes for efficiency tracking
        full_size = len(json.dumps(response.full)) if response.full else 0
        summary_size = len(response.summary) if response.summary else 0

        # Fire response hooks
        for hook in self.on_response:
            try:
                hook(response)
            except Exception:
                pass  # Don't let hooks break response

        # Complete telemetry tracking
        if self.telemetry and telemetry_id:
            self.telemetry.track_response(
                telemetry_id,
                error=error,
                error_msg=error_msg,
                full_size=full_size,
                summary_size=summary_size
            )

        return response

    def _generate_correlation_id(
        self,
        destination: str,
        tool_name: str,
        args: dict
    ) -> str:
        """Generate correlation ID from request parameters.

        Uses hash of args for deterministic IDs (same request = same ID).
        """
        content = json.dumps({
            "destination": destination,
            "tool": tool_name,
            "args": args
        }, sort_keys=True)
        hash_digest = hashlib.sha256(content.encode()).hexdigest()[:12]
        return f"req-{hash_digest}"

    def _get_backend_lock(self, server_name: str) -> RLock:
        """Get or create reentrant lock for a backend server.
        
        Uses RLock to allow recursive calls (e.g., _restore_workflow_state
        calling _forward_to_server while lock is held).
        """
        with self._lock:
            if server_name not in self._backend_locks:
                self._backend_locks[server_name] = RLock()
            return self._backend_locks[server_name]

    def _get_connection(self, server: ServerConfig) -> subprocess.Popen:
        """Get existing connection or spawn new one with handshake.

        Args:
            server: Target server config

        Returns:
            Live subprocess connection

        Raises:
            RuntimeError: If connection cannot be established
        """
        # Return existing connection if we have one
        if server.name in self._connections:
            return self._connections[server.name]

        # Spawn new process
        proc = subprocess.Popen(
            server.command,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1  # Line buffered
        )

        def send(msg: dict) -> None:
            """Send JSON-RPC message to server."""
            line = json.dumps(msg) + "\n"
            proc.stdin.write(line)  # type: ignore[union-attr]
            proc.stdin.flush()  # type: ignore[union-attr]

        def receive() -> dict:
            """Receive JSON-RPC response from server."""
            line = proc.stdout.readline()  # type: ignore[union-attr]
            if not line:
                raise RuntimeError("Server closed connection")
            return json.loads(line.strip())

        # MCP handshake
        try:
            send({
                "jsonrpc": "2.0",
                "id": 1,
                "method": "initialize",
                "params": {
                    "protocolVersion": "2024-11-05",
                    "capabilities": {},
                    "clientInfo": {
                        "name": "mcp-router",
                        "version": "1.0.0"
                    }
                }
            })

            init_response = receive()
            if "error" in init_response:
                proc.kill()
                raise RuntimeError(f"Initialize failed: {init_response['error']}")

            send({
                "jsonrpc": "2.0",
                "method": "notifications/initialized"
            })
        except Exception as e:
            proc.kill()
            raise RuntimeError(f"Handshake failed: {e}")

        # Store connection
        self._connections[server.name] = proc
        return proc

    def _forward_to_server(
        self,
        server: ServerConfig,
        tool_name: str,
        args: dict,
        _is_restore: bool = False
    ) -> dict:
        """Forward request to target MCP server.

        Uses persistent connection (spawns on first use, reuses thereafter).
        Per-backend lock ensures safe concurrent access.

        Args:
            server: Target server config
            tool_name: Tool to invoke
            args: Tool arguments
            _is_restore: Internal flag to prevent infinite recursion during state restore

        Returns:
            Response dict from target server
        """
        backend_lock = self._get_backend_lock(server.name)

        with backend_lock:
            try:
                # Check if this is a fresh connection (for state restoration)
                is_new_connection = server.name not in self._connections
                proc = self._get_connection(server)

                # Restore cached state if this is a fresh workflow backend
                if is_new_connection and server.name == "workflow" and not _is_restore:
                    self._restore_workflow_state(server.name)

                # Build request
                request_id = hash((tool_name, json.dumps(args, sort_keys=True))) & 0xFFFFFFFF

                if tool_name == "__list__":
                    # Special: get tool list
                    request = {
                        "jsonrpc": "2.0",
                        "id": request_id,
                        "method": "tools/list",
                        "params": {}
                    }
                else:
                    # Normal tool call
                    request = {
                        "jsonrpc": "2.0",
                        "id": request_id,
                        "method": "tools/call",
                        "params": {
                            "name": tool_name,
                            "arguments": args
                        }
                    }

                line = json.dumps(request) + "\n"
                proc.stdin.write(line)  # type: ignore[union-attr]
                proc.stdin.flush()  # type: ignore[union-attr]

                # Receive response with timeout to prevent indefinite blocking
                ready, _, _ = select.select([proc.stdout], [], [], 30.0)
                if not ready:
                    # Timeout - backend not responding, clean up connection
                    self._connections.pop(server.name, None)
                    return {"error": {"code": -32603, "message": f"Timeout waiting for {server.name}"}}

                response_line = proc.stdout.readline()  # type: ignore[union-attr]
                if not response_line:
                    # Connection died, remove and retry once
                    self._connections.pop(server.name, None)
                    return self._forward_to_server(server, tool_name, args)

                response = json.loads(response_line.strip())

                # Cache workflow state on successful operations
                if server.name == "workflow" and "error" not in response and not _is_restore:
                    self._cache_workflow_state(tool_name, args, response)

                return response

            except json.JSONDecodeError as e:
                self._connections.pop(server.name, None)
                return {"error": f"Invalid JSON response: {e}"}
            except Exception as e:
                self._connections.pop(server.name, None)
                return {"error": str(e)}

    # === Summarization ===

    def _summarize(self, response: dict) -> str:
        """Generate summary of response using configured LLM.

        Args:
            response: Response dict to summarize

        Returns:
            Summary string (or fallback on error)
        """
        content = json.dumps(response, indent=2)[:2000]

        prompt = f"""Summarize this MCP tool response in 1-2 concise sentences.
Focus on what was accomplished or returned.

Response:
{content}

Summary:"""

        result = self._llm_call(prompt)
        return result if result else self._fallback_summary(response)

    def _fallback_summary(self, response: dict) -> str:
        """Generate fallback summary when Haiku unavailable.

        Args:
            response: Response dict

        Returns:
            Basic summary string
        """
        if "error" in response:
            return f"Error: {response['error'][:100]}"

        # Try to extract meaningful info
        if "result" in response:
            result = response["result"]
            if isinstance(result, list):
                return f"Returned {len(result)} items"
            elif isinstance(result, dict):
                keys = list(result.keys())[:3]
                return f"Returned object with keys: {', '.join(keys)}"
            elif isinstance(result, str):
                return f"Returned string ({len(result)} chars)"

        return f"Response received ({len(json.dumps(response))} chars)"

    # Output schemas for structured extraction
    TOOL_SCHEMAS: dict[str, dict] = {
        "grep": {
            "description": "Search results grouped by file with line numbers",
            "schema": {
                "files": "list of matching file paths",
                "by_file": "dict mapping filepath to list of line numbers where matches occur",
                "match_count": "total number of matches"
            }
        },
        "glob": {
            "description": "File listing grouped by directory",
            "schema": {
                "by_directory": "dict mapping directory path to list of filenames in that directory",
                "total": "total number of files found"
            }
        },
        "bash": {
            "description": "Command execution result. If output contains [stderr] marker, that indicates error output.",
            "schema": {
                "exit_code": "0 for success, non-zero if [stderr] present or command failed",
                "line_count": "number of output lines",
                "preview": "first 5 lines of output (list of strings)",
                "error": "content after [stderr] marker if present, null otherwise"
            }
        },
        "read_file": {
            "description": "File contents",
            "schema": {
                "line_count": "number of lines in file",
                "char_count": "number of characters",
                "preview": "first 10 lines of content"
            }
        },
        "write_file": {
            "description": "File write result",
            "schema": {
                "success": "true if file was written successfully",
                "error": "error message if failed, null otherwise"
            }
        },
        "edit_file": {
            "description": "File edit result",
            "schema": {
                "success": "true if edit was applied successfully",
                "error": "error message if failed, null otherwise"
            }
        }
    }

    GENERIC_SCHEMA = {
        "description": "Generic tool output",
        "schema": {
            "char_count": "total characters in output",
            "preview": "first 500 characters of output",
            "truncated": "true if output was truncated"
        }
    }

    def _extract_summary(self, tool_name: str, response: dict) -> str:
        """Generate structured summary using LLM to extract into schema.

        Args:
            tool_name: Name of the tool that produced the response
            response: Response dict from backend

        Returns:
            JSON string with structured summary
        """
        if "error" in response:
            return json.dumps({"error": str(response["error"])[:200]})

        # Get raw content from MCP response
        content = self._extract_content(response)

        # Skip LLM for small responses (workflow state, simple results)
        if len(content) < 500:
            return json.dumps({"preview": content[:200], "size": len(content)})

        # For bash with stderr, use fallback directly (LLM struggles with [stderr] marker)
        if tool_name == "bash" and "[stderr]" in content:
            return self._fallback_extract(tool_name, content)

        # Get schema for this tool (or generic)
        tool_schema = self.TOOL_SCHEMAS.get(tool_name, self.GENERIC_SCHEMA)

        # Use LLM to extract into schema
        prompt = f"""Transform this tool output into the following JSON schema.
Return ONLY valid JSON, no explanation.
Limit any lists to first 10 items max.

Schema: {json.dumps(tool_schema["schema"])}
Tool output (truncated to 2000 chars):
{content[:2000]}

JSON:"""

        result = self._llm_call(prompt)

        # Validate it's JSON, fallback if not
        if result:
            try:
                json.loads(result)
                return result
            except json.JSONDecodeError:
                pass

        # Fallback: basic extraction without LLM
        return self._fallback_extract(tool_name, content)

    def _extract_content(self, response: dict) -> str:
        """Extract raw text content from MCP response."""
        if "result" in response:
            result = response["result"]
            if isinstance(result, dict):
                content_list = result.get("content", [])
                if content_list and isinstance(content_list[0], dict):
                    return content_list[0].get("text", "")
            elif isinstance(result, str):
                return result
        return json.dumps(response)

    def _fallback_extract(self, tool_name: str, content: str) -> str:
        """Fallback extraction when LLM unavailable."""
        lines = content.split("\n")

        if tool_name in ("write_file", "edit_file"):
            return json.dumps({"success": "error" not in content.lower()})

        if tool_name == "bash":
            # [stderr] marker indicates error output was present
            has_stderr = "[stderr]" in content
            stderr_content = None
            if has_stderr:
                parts = content.split("[stderr]")
                stderr_content = parts[1].strip() if len(parts) > 1 else "stderr present"
            return json.dumps({
                "exit_code": 1 if has_stderr else 0,
                "line_count": len(lines),
                "preview": lines[:5],
                "error": stderr_content
            })

        # Generic fallback
        return json.dumps({
            "char_count": len(content),
            "preview": content[:500],
            "truncated": len(content) > 500
        })


def analyze_telemetry_trends(telemetry: TelemetryCollector) -> dict:
    """Analyze telemetry data for trends and effectiveness.

    Returns analysis of token usage patterns and optimization effectiveness.
    Works with v2 telemetry schema.
    """
    summary = telemetry.get_summary()
    events = summary.get("recent_events", [])
    agg = summary.get("aggregates", {})

    analysis = {
        "session_id": summary.get("session_id", ""),
        "total_events": summary.get("event_count", 0),
        "today": summary.get("today", ""),
        "totals": agg.get("totals", {}),
        "trends": {},
        "recommendations": []
    }

    if len(events) >= 10:
        # Compare first half vs second half of events
        mid = len(events) // 2
        first_half = events[:mid]
        second_half = events[mid:]

        first_tokens = sum(e.get("tokens_est", 0) for e in first_half)
        second_tokens = sum(e.get("tokens_est", 0) for e in second_half)

        if first_tokens > 0:
            change_pct = ((second_tokens - first_tokens) / first_tokens) * 100
            analysis["trends"]["token_change_pct"] = round(change_pct, 1)
            analysis["trends"]["first_half_tokens"] = first_tokens
            analysis["trends"]["second_half_tokens"] = second_tokens

            if change_pct < -10:
                analysis["trends"]["verdict"] = "IMPROVING"
                analysis["recommendations"].append(
                    "Token usage is decreasing - optimization measures appear effective"
                )
            elif change_pct > 10:
                analysis["trends"]["verdict"] = "INCREASING"
                analysis["recommendations"].append(
                    "Token usage is increasing - consider reviewing recent tool usage patterns"
                )
            else:
                analysis["trends"]["verdict"] = "STABLE"

    # Check for high-call tools (v2 schema has counts, not token totals per tool)
    by_tool = agg.get("by_tool", {})
    high_call_tools = [
        (tool, count)
        for tool, count in by_tool.items()
        if isinstance(count, int) and count > 50
    ]
    if high_call_tools:
        sorted_tools = sorted(high_call_tools, key=lambda x: x[1], reverse=True)[:3]
        analysis["top_tool_callers"] = [
            {"tool": t, "calls": v} for t, v in sorted_tools
        ]
        analysis["recommendations"].append(
            f"High call count in: {', '.join(t for t, _ in sorted_tools)}"
        )

    # Timing analysis
    timing = agg.get("timing", {})
    by_backend = timing.get("by_backend", {})
    slow_backends = [
        (backend, stats.get("avg_ms", 0))
        for backend, stats in by_backend.items()
        if isinstance(stats, dict) and stats.get("avg_ms", 0) > 1000
    ]
    if slow_backends:
        analysis["slow_backends"] = [
            {"backend": b, "avg_ms": round(ms, 1)} for b, ms in slow_backends
        ]
        analysis["recommendations"].append(
            f"Slow response times from: {', '.join(b for b, _ in slow_backends)}"
        )

    # Summarization efficiency
    efficiency = agg.get("efficiency", {})
    tokens_saved = efficiency.get("tokens_saved_est", 0)
    if tokens_saved > 0:
        analysis["tokens_saved_est"] = tokens_saved
        analysis["recommendations"].append(
            f"Summarization saved approximately {tokens_saved} tokens"
        )

    return analysis


# === stdio Server ===

def start_stdio_server(router: MCPRouter):
    """Run stdio-based MCP server loop.

    Reads JSON-RPC requests from stdin, routes through router,
    writes responses to stdout.

    Implements MCP protocol:
    - initialize/initialized handshake
    - tools/list (aggregates from all backends, prefixes tool names)
    - tools/call (routes based on prefix)
    """
    def send(msg: dict) -> None:
        print(json.dumps(msg), flush=True)

    def list_all_tools() -> list[dict]:
        """Get tools from all backends, prefix names with backend."""
        # Router's own tools
        all_tools = [
            {
                "name": "router__ping",
                "description": "Test tool that returns a simple message",
                "inputSchema": {"type": "object", "properties": {}},
            },
            {
                "name": "router__telemetry",
                "description": "Get real-time telemetry data (tool usage, tokens, errors, timing)",
                "inputSchema": {"type": "object", "properties": {}},
            },
            {
                "name": "router__telemetry_analysis",
                "description": "Get analysis of token usage trends and optimization effectiveness",
                "inputSchema": {"type": "object", "properties": {}},
            },
            {
                "name": "router__clear_workflow_cache",
                "description": "Clear cached workflow state. Pass workflow_id to clear specific workflow, or omit for all.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "workflow_id": {"type": "string", "description": "Workflow ID to clear (optional, omit for all)"}
                    }
                },
            },
            # Event system pseudo-tools (handled by hooks, not router)
            {
                "name": "router__request",
                "description": "Async tool request. Returns correlation_id. Poll router__poll for response.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "tool": {"type": "string", "description": "Tool name (e.g., serena__find_symbol)"},
                        "args": {"type": "object", "description": "Tool arguments"}
                    },
                    "required": ["tool", "args"]
                }
            },
            {
                "name": "router__poll",
                "description": "Poll for async response by correlation_id.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "correlation_id": {"type": "string", "description": "Correlation ID from router__request"}
                    },
                    "required": ["correlation_id"]
                }
            },
            {
                "name": "router__publish",
                "description": "Publish event to topic.",
                "inputSchema": {
                    "type": "object",
                    "properties": {
                        "topic": {"type": "string", "description": "Event topic"},
                        "data": {"type": "object", "description": "Event data"}
                    },
                    "required": ["topic", "data"]
                }
            },
            {
                "name": "router__list_tools",
                "description": "List all available tools.",
                "inputSchema": {"type": "object", "properties": {}}
            },
        ]
        for server in router.list_servers():
            name = server["name"]
            prefix = server.get("tool_prefix") or name

            # Get tools from this backend
            try:
                response = router._forward_to_server(
                    router._servers[name],
                    "__list__",  # Special: triggers tools/list
                    {}
                )
                if "result" in response and "tools" in response["result"]:
                    for tool in response["result"]["tools"]:
                        # Prefix tool name
                        tool["name"] = f"{prefix}__{tool['name']}"
                        all_tools.append(tool)
            except Exception:
                pass  # Skip failed backends
        return all_tools

    _router_log("stdio", "Server started, waiting for requests...")

    for line in sys.stdin:
        # Log raw input BEFORE parsing
        _router_log("stdio", f"RAW_INPUT len={len(line)} preview={line[:100]!r}")

        request_id = None
        try:
            request = json.loads(line.strip())
            method = request.get("method", "")
            params = request.get("params", {})
            request_id = request.get("id")

            # Log all incoming requests
            if method == "tools/call":
                tool_name = params.get("name", "unknown")
                _router_log("stdio", f"RECV tools/call tool={tool_name} id={request_id}")
            elif method not in ("notifications/initialized",):
                _router_log("stdio", f"RECV method={method} id={request_id}")

            # MCP handshake
            if method == "initialize":
                result = {
                    "protocolVersion": "2024-11-05",
                    "capabilities": {"tools": {}},
                    "serverInfo": {
                        "name": "mcp-router",
                        "version": "1.0.0"
                    }
                }
            elif method == "notifications/initialized":
                continue  # Notification, no response

            # Tool discovery
            elif method == "tools/list":
                result = {"tools": list_all_tools()}

            # Tool execution - parse prefix to route
            elif method == "tools/call":
                tool_name = params.get("name", "")
                args = params.get("arguments", {})

                # Handle router's own tools first
                if tool_name == "router__ping":
                    result = {"content": [{"type": "text", "text": "pong! Router is working."}]}

                elif tool_name == "router__telemetry":
                    if router.telemetry:
                        summary = router.telemetry.get_summary()
                        summary["socket_stats"] = router.get_socket_stats()
                        result = {"content": [{"type": "text", "text": json.dumps(summary, indent=2)}]}
                    else:
                        result = {"content": [{"type": "text", "text": "Telemetry not enabled"}]}

                elif tool_name == "router__telemetry_analysis":
                    if router.telemetry:
                        analysis = analyze_telemetry_trends(router.telemetry)
                        result = {"content": [{"type": "text", "text": json.dumps(analysis, indent=2)}]}
                    else:
                        result = {"content": [{"type": "text", "text": "Telemetry not enabled"}]}

                elif tool_name == "router__clear_workflow_cache":
                    workflow_id = args.get("workflow_id")
                    result_data = router.clear_workflow_cache(workflow_id)
                    result = {"content": [{"type": "text", "text": json.dumps(result_data, indent=2)}]}

                # Parse prefix__toolname for backend routing
                elif "__" in tool_name:
                    prefix, actual_tool = tool_name.split("__", 1)
                    # Find backend by prefix
                    destination = None
                    for server in router.list_servers():
                        if server.get("tool_prefix") == prefix or server["name"] == prefix:
                            destination = server["name"]
                            break
                    if not destination:
                        result = {"content": [{"type": "text", "text": f"Error: Unknown backend prefix: {prefix}"}], "isError": True}
                    elif "content_id" in args:
                        # Two-step retrieval: return full content for given content_id
                        full_result = router.get_full_content(args["content_id"])
                        if "error" in full_result:
                            result = {"content": [{"type": "text", "text": f"Error: {full_result['error']}"}], "isError": True}
                        else:
                            result = {"content": [{"type": "text", "text": json.dumps(full_result)}]}
                    else:
                        response = router.route(destination, actual_tool, args)
                        # Return {summary, full} envelope so Claude can read summary first
                        backend_result = response.full
                        if isinstance(backend_result, dict) and "error" in backend_result:
                            result = {"content": [{"type": "text", "text": f"Error: {backend_result['error']}"}], "isError": True}
                        else:
                            # Extract actual content from backend response
                            if isinstance(backend_result, dict) and "result" in backend_result:
                                full_content = backend_result["result"]
                            else:
                                full_content = backend_result

                            # Return structured envelope with summary and full
                            envelope = {
                                "summary": response.summary,
                                "full": full_content
                            }
                            result = {"content": [{"type": "text", "text": json.dumps(envelope)}]}
                else:
                    result = {"content": [{"type": "text", "text": "Tool name must be prefixed: prefix__tool"}], "isError": True}

            # Router management API
            elif method == "router_register":
                result = router.register_server(**params)
            elif method == "router_list":
                result = router.list_servers()
            elif method == "router_unregister":
                result = router.unregister_server(**params)

            else:
                result = {"error": f"Unknown method: {method}"}

            # Write response (skip for notifications)
            if request_id is not None:
                response_msg = {
                    "jsonrpc": "2.0",
                    "id": request_id,
                    "result": result
                }
                _router_log("stdio", f"SEND id={request_id} result_size={len(json.dumps(result))}")
                send(response_msg)

        except json.JSONDecodeError as e:
            _router_log("stdio", f"ERROR parse error: {e}", "ERROR")
            send({
                "jsonrpc": "2.0",
                "id": request_id,
                "error": {"code": -32700, "message": f"Parse error: {e}"}
            })
        except Exception as e:
            _router_log("stdio", f"ERROR exception: {str(e)[:100]}", "ERROR")
            send({
                "jsonrpc": "2.0",
                "id": request_id,
                "error": {"code": -32603, "message": str(e)}
            })


if __name__ == "__main__":
    router = MCPRouter()

    # Auto-register default server from env if specified
    default_server = os.environ.get("MCP_ROUTER_DEFAULT_SERVER")
    if default_server:
        router.register_server("default", default_server.split(), {})

    # Start socket listener for external clients (hooks, CLIs)
    port = router.start_socket_listener()
    sys.stderr.write(f"Router socket listener started on port {port}\n")

    try:
        start_stdio_server(router)
    finally:
        router.shutdown()
