#!/usr/bin/env python3
"""
Pre-Compacting Hook - Auto-write handoff before context compression

Automatically generates a handoff document before conversation compacting
to preserve important context, decisions, and progress.
"""

import json
import sys
from datetime import datetime
from pathlib import Path

try:
    from hook_logging import log_error, log_warning, log_info, log_debug, ConfigError, StateError
except ImportError:
    # Fallback: define minimal logging functions
    def log_error(msg, **kw): pass
    def log_warning(msg, **kw): pass
    def log_info(msg, **kw): pass
    def log_debug(msg, **kw): pass
    class ConfigError(Exception): pass
    class StateError(Exception): pass
HANDOFF_FILE = Path(__file__).parent.parent / "HANDOFF.md"
STATE_DIR = Path.home() / ".claude/plugins/agent-swarm/.state"

def extract_session_info():
    """Extract key information from the current session."""

    # Try to load session state
    session_file = STATE_DIR / "session.json"
    if session_file.exists():
        try:
            session = json.loads(session_file.read_text())
            phase = session.get("phase", "unknown")
            task = session.get("task_summary", "No task specified")
        except Exception:
            phase = "unknown"
            task = "No task specified"
    else:
        phase = "unknown"
        task = "No task specified"

    # Load metrics if available
    metrics_file = STATE_DIR / "metrics.json"
    metrics = {}
    if metrics_file.exists():
        try:
            metrics = json.loads(metrics_file.read_text())
        except Exception as e:
            log_warning(f"Caught exception: {e}")

    return {
        "phase": phase,
        "task": task,
        "metrics": metrics,
        "timestamp": datetime.now().isoformat()
    }

def generate_handoff(session_info):
    """Generate handoff document content."""

    timestamp = datetime.now().strftime("%Y-%m-%d %I:%M%p")

    handoff = f"""# Session Handoff - Auto-Generated

**Date:** {timestamp}
**Status:** 🔄 IN PROGRESS - Pre-compacting checkpoint

---

## 📍 Current State

**Phase:** {session_info['phase']}
**Task:** {session_info['task']}

---

## ⚠️ IMPORTANT: Context is about to be compacted

This handoff was automatically generated before conversation compacting.
Key context from the current session will be condensed.

### What to do:

1. **Review current progress** - Check what's been completed
2. **Note any blockers** - Document issues encountered
3. **Update task status** - Mark completed items
4. **Preserve decisions** - Record important choices made

---

## 📊 Session Metrics

"""

    metrics = session_info.get("metrics", {})
    if metrics:
        tools = metrics.get("tools_by_type", {})
        if tools:
            handoff += "**Tool Usage:**\n"
            for tool, count in sorted(tools.items(), key=lambda x: x[1], reverse=True)[:10]:
                handoff += f"- {tool}: {count}\n"
            handoff += "\n"

        efficiency = metrics.get("efficiency_score", 0)
        if efficiency:
            handoff += f"**Efficiency Score:** {efficiency:.1f}%\n\n"

    handoff += """---

## 📝 Next Steps

**Before resuming:**
1. Review this handoff
2. Update with current progress
3. Continue from last checkpoint

---

## 🔧 Quick Commands

```bash
# View current state
cat ~/.claude/plugins/agent-swarm/HANDOFF.md

# Generate metrics
python3 ~/.claude/plugins/agent-swarm/scripts/charts.py dashboard

# Check session status
cat ~/.claude/plugins/agent-swarm/.state/session.json
```

---

**Auto-generated by pre-compacting hook**
"""

    return handoff


COMPACTION_STATE_FILE = STATE_DIR / "compaction_state.json"

# Flags that should persist across compaction (same conversation)
PERSISTENT_FLAGS = [
    "user_approved_commit",
    "tests_executed",
    "verify_signal_given",
]

def save_compaction_state():
    """Save persistent flags before compaction so they survive session reset."""
    session_file = STATE_DIR / "session.json"
    
    if not session_file.exists():
        return False
    
    try:
        session = json.loads(session_file.read_text())
        
        # Extract only persistent flags that are set
        compaction_state = {
            "saved_at": datetime.now().isoformat(),
            "flags": {}
        }
        
        for flag in PERSISTENT_FLAGS:
            if session.get(flag):
                compaction_state["flags"][flag] = session[flag]
        
        # Only write if there are flags to preserve
        if compaction_state["flags"]:
            COMPACTION_STATE_FILE.write_text(json.dumps(compaction_state, indent=2))
            return True
        
        return False
    except (IOError, json.JSONDecodeError):
        return False  # Silent fallback - state save is best-effort

def main():
    """Pre-compacting hook entry point."""

    # Read hook input
    try:
        input_data = json.loads(sys.stdin.read())
    except json.JSONDecodeError:
        input_data = {}  # Empty input is acceptable

    # Save persistent flags before compaction
    flags_saved = save_compaction_state()

    # Extract session information
    session_info = extract_session_info()

    # Generate handoff
    handoff_content = generate_handoff(session_info)

    # Write handoff file
    try:
        HANDOFF_FILE.write_text(handoff_content)
        message = f"✓ Handoff auto-generated: {HANDOFF_FILE.name}"
    except Exception as e:
        message = f"⚠️ Failed to write handoff: {e}"

    # Build status message
    status_parts = [f"[PRE-COMPACTING] {message}"]
    if flags_saved:
        status_parts.append("   ✓ Approval state preserved for session continuity")
    status_parts.append("   Context will be compacted - review handoff for preserved state")

    # Return result
    output = {
        "systemMessage": "\n".join(status_parts)
    }

    print(json.dumps(output))

if __name__ == "__main__":
    main()
