#!/usr/bin/env python3
"""
Pre-Compacting Hook - Auto-write handoff before context compression

Automatically generates a handoff document before conversation compacting
to preserve important context, decisions, and progress.
"""

import fcntl
import json
import sys
from datetime import datetime
from pathlib import Path

try:
    from hook_logging import log_error, log_warning, log_info, log_debug, ConfigError, StateError
except ImportError:
    # Fallback: define minimal logging functions
    def log_error(msg, **kw):
        pass
    def log_warning(msg, **kw):
        pass
    def log_info(msg, **kw):
        pass
    def log_debug(msg, **kw):
        pass
    class ConfigError(Exception):
        pass
    class StateError(Exception):
        pass

STATE_DIR = Path(__file__).resolve().parent.parent / ".state"


def detect_handoff_scope(cwd: Path) -> Path:
    """
    Detect appropriate handoff scope and return path.

    Priority:
    1. Git repo root (project-scoped) → <repo>/.claude/HANDOFF.md
    2. Current working directory (directory-scoped) → <cwd>/.context/HANDOFF.md
    3. Global scratch (fallback) → ~/.claude/docs/scratch/HANDOFF.md
    """
    # Check for git root by walking up
    current = cwd.resolve()
    while current != current.parent:
        if (current / ".git").exists():
            # Found git repo
            handoff_dir = current / ".claude"
            handoff_dir.mkdir(exist_ok=True)
            return handoff_dir / "HANDOFF.md"
        current = current.parent

    # No git repo, use current directory
    if cwd.exists() and cwd.is_dir():
        handoff_dir = cwd / ".context"
        handoff_dir.mkdir(exist_ok=True)
        return handoff_dir / "HANDOFF.md"

    # Fallback to global
    global_dir = Path.home() / ".claude/docs/scratch"
    global_dir.mkdir(parents=True, exist_ok=True)
    return global_dir / "HANDOFF.md"

def extract_session_info():
    """Extract key information from the current session."""

    # Try to load session state
    session_file = STATE_DIR / "session.json"
    if session_file.exists():
        try:
            session = json.loads(session_file.read_text())
            phase = session.get("phase", "unknown")
            task = session.get("task_summary", "No task specified")
        except (json.JSONDecodeError, IOError) as e:
            log_debug(f"Failed to load session file: {e}")
            phase = "unknown"
            task = "No task specified"
    else:
        phase = "unknown"
        task = "No task specified"

    # Load metrics if available
    metrics_file = STATE_DIR / "metrics.json"
    metrics = {}
    if metrics_file.exists():
        try:
            metrics = json.loads(metrics_file.read_text())
        except Exception as e:
            log_warning(f"Caught exception: {e}")

    return {
        "phase": phase,
        "task": task,
        "metrics": metrics,
        "timestamp": datetime.now().isoformat()
    }

def generate_handoff(session_info):
    """Generate handoff document content."""

    timestamp = datetime.now().strftime("%Y-%m-%d %I:%M%p")

    handoff = f"""# Session Handoff - Auto-Generated

**Date:** {timestamp}
**Status:** 🔄 IN PROGRESS - Pre-compacting checkpoint

---

## 📍 Current State

**Phase:** {session_info['phase']}
**Task:** {session_info['task']}

---

## ⚠️ IMPORTANT: Context is about to be compacted

This handoff was automatically generated before conversation compacting.
Key context from the current session will be condensed.

### What to do:

1. **Review current progress** - Check what's been completed
2. **Note any blockers** - Document issues encountered
3. **Update task status** - Mark completed items
4. **Preserve decisions** - Record important choices made

---

## 📊 Session Metrics

"""

    metrics = session_info.get("metrics", {})
    if metrics:
        tools = metrics.get("tools_by_type", {})
        if tools:
            handoff += "**Tool Usage:**\n"
            for tool, count in sorted(tools.items(), key=lambda x: x[1], reverse=True)[:10]:
                handoff += f"- {tool}: {count}\n"
            handoff += "\n"

        efficiency = metrics.get("efficiency_score", 0)
        if efficiency:
            handoff += f"**Efficiency Score:** {efficiency:.1f}%\n\n"

    handoff += """---

## 📝 Next Steps

**Before resuming:**
1. Review this handoff
2. Update with current progress
3. Continue from last checkpoint

---

## 🔧 Quick Commands

```bash
# View current state
cat ~/.claude/plugins/agent-swarm/HANDOFF.md

# Generate metrics
python3 ~/.claude/plugins/agent-swarm/scripts/charts.py dashboard

# Check session status
cat ~/.claude/plugins/agent-swarm/.state/session.json
```

---

**Auto-generated by pre-compacting hook**
"""

    return handoff


COMPACTION_STATE_FILE = STATE_DIR / "compaction_state.json"

# Flags that should persist across compaction (same conversation)
PERSISTENT_FLAGS = [
    "user_approved_commit",
    "tests_executed",
    "verify_signal_given",
    "phase",  # Preserve workflow phase
    "workflow_invoked",  # Workflow should persist across compaction
]

# Flags that must be CLEARED on compaction (depend on message history)
MESSAGE_DEPENDENT_FLAGS = [
    "classification_given",
    "classification_type",
    "edits_this_response",
]

def save_compaction_state():
    """Save persistent flags before compaction so they survive session reset."""
    session_file = STATE_DIR / "session.json"
    
    if not session_file.exists():
        return False
    
    try:
        session = json.loads(session_file.read_text())
        
        # Extract only persistent flags that are set
        compaction_state = {
            "saved_at": datetime.now().isoformat(),
            "flags": {}
        }
        
        for flag in PERSISTENT_FLAGS:
            if session.get(flag):
                compaction_state["flags"][flag] = session[flag]
        
        # Only write if there are flags to preserve
        if compaction_state["flags"]:
            COMPACTION_STATE_FILE.write_text(json.dumps(compaction_state, indent=2))
            return True
        
        return False
    except (IOError, json.JSONDecodeError):
        return False  # Silent fallback - state save is best-effort

def main():
    """Pre-compacting hook entry point."""

    # Read hook input
    try:
        input_data = json.loads(sys.stdin.read())
    except json.JSONDecodeError:
        input_data = {}  # Empty input is acceptable

    # Get working directory for scoped handoffs
    cwd = Path(input_data.get("cwd", ".")).resolve()

    # Detect appropriate handoff scope
    handoff_file = detect_handoff_scope(cwd)

    # Save persistent flags before compaction
    flags_saved = save_compaction_state()

    # Extract session information
    session_info = extract_session_info()

    # Generate handoff
    handoff_content = generate_handoff(session_info)

    # Write handoff file with locking to prevent race conditions
    try:
        handoff_file.parent.mkdir(parents=True, exist_ok=True)
        with open(handoff_file, 'w') as f:
            fcntl.flock(f.fileno(), fcntl.LOCK_EX)
            f.write(handoff_content)
            fcntl.flock(f.fileno(), fcntl.LOCK_UN)
        message = f"✓ Handoff auto-generated: {handoff_file}"
    except Exception as e:
        message = f"⚠️ Failed to write handoff: {e}"

    # Build status message
    status_parts = [f"[PRE-COMPACTING] {message}"]
    if flags_saved:
        status_parts.append("   ✓ Approval state preserved for session continuity")
    status_parts.append("   Context will be compacted - review handoff for preserved state")

    # Return result
    output = {
        "systemMessage": "\n".join(status_parts)
    }

    print(json.dumps(output))

if __name__ == "__main__":
    main()
